DROP TABLE IF EXISTS tblOrder CASCADE;

create table tblOrder (
	order_id SERIAL PRIMARY KEY,
	customer_id INTEGER REFERENCES tblCustomer(customer_id),
	source VARCHAR(50)
);

insert into tblOrder (order_id, customer_id, source) values (1, 287, 'Reactive');
insert into tblOrder (order_id, customer_id, source) values (2, 750, 'protocol');
insert into tblOrder (order_id, customer_id, source) values (3, 151, 'Programmable');
insert into tblOrder (order_id, customer_id, source) values (4, 387, 'monitoring');
insert into tblOrder (order_id, customer_id, source) values (5, 257, 'challenge');
insert into tblOrder (order_id, customer_id, source) values (6, 25, 'installation');
insert into tblOrder (order_id, customer_id, source) values (7, 337, 'Multi-tiered');
insert into tblOrder (order_id, customer_id, source) values (8, 401, 'matrices');
insert into tblOrder (order_id, customer_id, source) values (9, 633, 'help-desk');
insert into tblOrder (order_id, customer_id, source) values (10, 52, 'context-sensitive');
insert into tblOrder (order_id, customer_id, source) values (11, 248, 'clear-thinking');
insert into tblOrder (order_id, customer_id, source) values (12, 681, 'Open-source');
insert into tblOrder (order_id, customer_id, source) values (13, 826, 'structure');
insert into tblOrder (order_id, customer_id, source) values (14, 242, 'fresh-thinking');
insert into tblOrder (order_id, customer_id, source) values (15, 903, 'projection');
insert into tblOrder (order_id, customer_id, source) values (16, 801, 'info-mediaries');
insert into tblOrder (order_id, customer_id, source) values (17, 479, 'static');
insert into tblOrder (order_id, customer_id, source) values (18, 48, 'zero defect');
insert into tblOrder (order_id, customer_id, source) values (19, 274, 'Focused');
insert into tblOrder (order_id, customer_id, source) values (20, 698, 'Synchronised');
insert into tblOrder (order_id, customer_id, source) values (21, 699, 'Cross-group');
insert into tblOrder (order_id, customer_id, source) values (22, 502, 'standardization');
insert into tblOrder (order_id, customer_id, source) values (23, 52, 'model');
insert into tblOrder (order_id, customer_id, source) values (24, 934, 'matrices');
insert into tblOrder (order_id, customer_id, source) values (25, 699, 'logistical');
insert into tblOrder (order_id, customer_id, source) values (26, 137, 'open system');
insert into tblOrder (order_id, customer_id, source) values (27, 254, 'Object-based');
insert into tblOrder (order_id, customer_id, source) values (28, 474, 'collaboration');
insert into tblOrder (order_id, customer_id, source) values (29, 978, 'challenge');
insert into tblOrder (order_id, customer_id, source) values (30, 677, 'bifurcated');
insert into tblOrder (order_id, customer_id, source) values (31, 754, 'knowledge user');
insert into tblOrder (order_id, customer_id, source) values (32, 927, 'actuating');
insert into tblOrder (order_id, customer_id, source) values (33, 279, 'neural-net');
insert into tblOrder (order_id, customer_id, source) values (34, 321, 'zero defect');
insert into tblOrder (order_id, customer_id, source) values (35, 248, 'bi-directional');
insert into tblOrder (order_id, customer_id, source) values (36, 882, 'capability');
insert into tblOrder (order_id, customer_id, source) values (37, 326, 'Operative');
insert into tblOrder (order_id, customer_id, source) values (38, 773, 'Open-architected');
insert into tblOrder (order_id, customer_id, source) values (39, 719, 'extranet');
insert into tblOrder (order_id, customer_id, source) values (40, 507, 'Expanded');
insert into tblOrder (order_id, customer_id, source) values (41, 356, 'Switchable');
insert into tblOrder (order_id, customer_id, source) values (42, 966, 'intermediate');
insert into tblOrder (order_id, customer_id, source) values (43, 568, 'internet solution');
insert into tblOrder (order_id, customer_id, source) values (44, 162, 'Digitized');
insert into tblOrder (order_id, customer_id, source) values (45, 918, 'Horizontal');
insert into tblOrder (order_id, customer_id, source) values (46, 732, 'encryption');
insert into tblOrder (order_id, customer_id, source) values (47, 574, 'Organized');
insert into tblOrder (order_id, customer_id, source) values (48, 808, 'Function-based');
insert into tblOrder (order_id, customer_id, source) values (49, 112, 'task-force');
insert into tblOrder (order_id, customer_id, source) values (50, 287, 'contextually-based');
insert into tblOrder (order_id, customer_id, source) values (51, 863, 'stable');
insert into tblOrder (order_id, customer_id, source) values (52, 950, 'artificial intelligence');
insert into tblOrder (order_id, customer_id, source) values (53, 764, 'Persistent');
insert into tblOrder (order_id, customer_id, source) values (54, 639, 'content-based');
insert into tblOrder (order_id, customer_id, source) values (55, 225, 'well-modulated');
insert into tblOrder (order_id, customer_id, source) values (56, 790, 'orchestration');
insert into tblOrder (order_id, customer_id, source) values (57, 44, 'Universal');
insert into tblOrder (order_id, customer_id, source) values (58, 892, 'local area network');
insert into tblOrder (order_id, customer_id, source) values (59, 185, 'user-facing');
insert into tblOrder (order_id, customer_id, source) values (60, 986, 'logistical');
insert into tblOrder (order_id, customer_id, source) values (61, 658, 'client-server');
insert into tblOrder (order_id, customer_id, source) values (62, 91, 'system engine');
insert into tblOrder (order_id, customer_id, source) values (63, 69, 'logistical');
insert into tblOrder (order_id, customer_id, source) values (64, 126, 'motivating');
insert into tblOrder (order_id, customer_id, source) values (65, 73, 'Down-sized');
insert into tblOrder (order_id, customer_id, source) values (66, 986, 'protocol');
insert into tblOrder (order_id, customer_id, source) values (67, 459, 'Pre-emptive');
insert into tblOrder (order_id, customer_id, source) values (68, 962, 'system engine');
insert into tblOrder (order_id, customer_id, source) values (69, 171, 'Synchronised');
insert into tblOrder (order_id, customer_id, source) values (70, 971, 'infrastructure');
insert into tblOrder (order_id, customer_id, source) values (71, 334, 'Organic');
insert into tblOrder (order_id, customer_id, source) values (72, 317, 'leading edge');
insert into tblOrder (order_id, customer_id, source) values (73, 75, 'user-facing');
insert into tblOrder (order_id, customer_id, source) values (74, 106, 'Advanced');
insert into tblOrder (order_id, customer_id, source) values (75, 228, 'concept');
insert into tblOrder (order_id, customer_id, source) values (76, 689, 'Centralized');
insert into tblOrder (order_id, customer_id, source) values (77, 397, 'database');
insert into tblOrder (order_id, customer_id, source) values (78, 848, 'Integrated');
insert into tblOrder (order_id, customer_id, source) values (79, 48, 'website');
insert into tblOrder (order_id, customer_id, source) values (80, 574, 'groupware');
insert into tblOrder (order_id, customer_id, source) values (81, 486, 'budgetary management');
insert into tblOrder (order_id, customer_id, source) values (82, 404, 'analyzing');
insert into tblOrder (order_id, customer_id, source) values (83, 640, 'challenge');
insert into tblOrder (order_id, customer_id, source) values (84, 676, 'info-mediaries');
insert into tblOrder (order_id, customer_id, source) values (85, 727, 'open architecture');
insert into tblOrder (order_id, customer_id, source) values (86, 204, 'ability');
insert into tblOrder (order_id, customer_id, source) values (87, 738, 'Inverse');
insert into tblOrder (order_id, customer_id, source) values (88, 305, 'exuding');
insert into tblOrder (order_id, customer_id, source) values (89, 541, 'empowering');
insert into tblOrder (order_id, customer_id, source) values (90, 710, 'static');
insert into tblOrder (order_id, customer_id, source) values (91, 84, 'Reduced');
insert into tblOrder (order_id, customer_id, source) values (92, 85, 'dynamic');
insert into tblOrder (order_id, customer_id, source) values (93, 361, 'success');
insert into tblOrder (order_id, customer_id, source) values (94, 37, 'Robust');
insert into tblOrder (order_id, customer_id, source) values (95, 563, 'Upgradable');
insert into tblOrder (order_id, customer_id, source) values (96, 159, 'eco-centric');
insert into tblOrder (order_id, customer_id, source) values (97, 846, 'maximized');
insert into tblOrder (order_id, customer_id, source) values (98, 179, 'Reverse-engineered');
insert into tblOrder (order_id, customer_id, source) values (99, 638, 'Programmable');
insert into tblOrder (order_id, customer_id, source) values (100, 168, 'optimizing');
insert into tblOrder (order_id, customer_id, source) values (101, 465, 'Pre-emptive');
insert into tblOrder (order_id, customer_id, source) values (102, 475, 'background');
insert into tblOrder (order_id, customer_id, source) values (103, 825, 'optimizing');
insert into tblOrder (order_id, customer_id, source) values (104, 977, 'solution-oriented');
insert into tblOrder (order_id, customer_id, source) values (105, 655, 'context-sensitive');
insert into tblOrder (order_id, customer_id, source) values (106, 13, 'database');
insert into tblOrder (order_id, customer_id, source) values (107, 438, 'encompassing');
insert into tblOrder (order_id, customer_id, source) values (108, 500, 'Focused');
insert into tblOrder (order_id, customer_id, source) values (109, 344, 'Enhanced');
insert into tblOrder (order_id, customer_id, source) values (110, 894, 'analyzing');
insert into tblOrder (order_id, customer_id, source) values (111, 194, 'Secured');
insert into tblOrder (order_id, customer_id, source) values (112, 676, 'product');
insert into tblOrder (order_id, customer_id, source) values (113, 336, 'leverage');
insert into tblOrder (order_id, customer_id, source) values (114, 61, 'infrastructure');
insert into tblOrder (order_id, customer_id, source) values (115, 172, 'bottom-line');
insert into tblOrder (order_id, customer_id, source) values (116, 417, '24/7');
insert into tblOrder (order_id, customer_id, source) values (117, 232, 'Seamless');
insert into tblOrder (order_id, customer_id, source) values (118, 924, 'emulation');
insert into tblOrder (order_id, customer_id, source) values (119, 676, 'contextually-based');
insert into tblOrder (order_id, customer_id, source) values (120, 585, 'Persevering');
insert into tblOrder (order_id, customer_id, source) values (121, 271, 'monitoring');
insert into tblOrder (order_id, customer_id, source) values (122, 546, 'Reverse-engineered');
insert into tblOrder (order_id, customer_id, source) values (123, 730, 'value-added');
insert into tblOrder (order_id, customer_id, source) values (124, 453, 'middleware');
insert into tblOrder (order_id, customer_id, source) values (125, 533, 'framework');
insert into tblOrder (order_id, customer_id, source) values (126, 371, 'pricing structure');
insert into tblOrder (order_id, customer_id, source) values (127, 297, 'Face to face');
insert into tblOrder (order_id, customer_id, source) values (128, 50, 'Down-sized');
insert into tblOrder (order_id, customer_id, source) values (129, 794, 'asynchronous');
insert into tblOrder (order_id, customer_id, source) values (130, 395, 'hub');
insert into tblOrder (order_id, customer_id, source) values (131, 338, 'User-centric');
insert into tblOrder (order_id, customer_id, source) values (132, 685, 'challenge');
insert into tblOrder (order_id, customer_id, source) values (133, 584, 'Front-line');
insert into tblOrder (order_id, customer_id, source) values (134, 208, 'real-time');
insert into tblOrder (order_id, customer_id, source) values (135, 314, 'scalable');
insert into tblOrder (order_id, customer_id, source) values (136, 579, 'capacity');
insert into tblOrder (order_id, customer_id, source) values (137, 86, 'real-time');
insert into tblOrder (order_id, customer_id, source) values (138, 34, 'Multi-channelled');
insert into tblOrder (order_id, customer_id, source) values (139, 171, 'Cross-group');
insert into tblOrder (order_id, customer_id, source) values (140, 484, '24 hour');
insert into tblOrder (order_id, customer_id, source) values (141, 912, 'workforce');
insert into tblOrder (order_id, customer_id, source) values (142, 502, 'intranet');
insert into tblOrder (order_id, customer_id, source) values (143, 203, 'Down-sized');
insert into tblOrder (order_id, customer_id, source) values (144, 891, 'systematic');
insert into tblOrder (order_id, customer_id, source) values (145, 91, 'Seamless');
insert into tblOrder (order_id, customer_id, source) values (146, 795, 'time-frame');
insert into tblOrder (order_id, customer_id, source) values (147, 466, 'Front-line');
insert into tblOrder (order_id, customer_id, source) values (148, 791, 'Future-proofed');
insert into tblOrder (order_id, customer_id, source) values (149, 304, 'next generation');
insert into tblOrder (order_id, customer_id, source) values (150, 83, 'workforce');
insert into tblOrder (order_id, customer_id, source) values (151, 640, 'Right-sized');
insert into tblOrder (order_id, customer_id, source) values (152, 259, 'portal');
insert into tblOrder (order_id, customer_id, source) values (153, 289, 'Front-line');
insert into tblOrder (order_id, customer_id, source) values (154, 183, 'De-engineered');
insert into tblOrder (order_id, customer_id, source) values (155, 872, 'forecast');
insert into tblOrder (order_id, customer_id, source) values (156, 198, 'Customer-focused');
insert into tblOrder (order_id, customer_id, source) values (157, 377, 'De-engineered');
insert into tblOrder (order_id, customer_id, source) values (158, 545, 'transitional');
insert into tblOrder (order_id, customer_id, source) values (159, 328, 'grid-enabled');
insert into tblOrder (order_id, customer_id, source) values (160, 216, 'Seamless');
insert into tblOrder (order_id, customer_id, source) values (161, 941, 'hardware');
insert into tblOrder (order_id, customer_id, source) values (162, 901, 'product');
insert into tblOrder (order_id, customer_id, source) values (163, 929, 'zero administration');
insert into tblOrder (order_id, customer_id, source) values (164, 615, 'holistic');
insert into tblOrder (order_id, customer_id, source) values (165, 291, 'solution-oriented');
insert into tblOrder (order_id, customer_id, source) values (166, 951, 'motivating');
insert into tblOrder (order_id, customer_id, source) values (167, 861, 'Universal');
insert into tblOrder (order_id, customer_id, source) values (168, 325, 'algorithm');
insert into tblOrder (order_id, customer_id, source) values (169, 575, 'transitional');
insert into tblOrder (order_id, customer_id, source) values (170, 899, 'toolset');
insert into tblOrder (order_id, customer_id, source) values (171, 484, 'Monitored');
insert into tblOrder (order_id, customer_id, source) values (172, 815, 'hardware');
insert into tblOrder (order_id, customer_id, source) values (173, 566, 'paradigm');
insert into tblOrder (order_id, customer_id, source) values (174, 351, 'system-worthy');
insert into tblOrder (order_id, customer_id, source) values (175, 268, 'zero defect');
insert into tblOrder (order_id, customer_id, source) values (176, 54, 'encompassing');
insert into tblOrder (order_id, customer_id, source) values (177, 227, 'Exclusive');
insert into tblOrder (order_id, customer_id, source) values (178, 204, 'standardization');
insert into tblOrder (order_id, customer_id, source) values (179, 535, 'Progressive');
insert into tblOrder (order_id, customer_id, source) values (180, 765, 'capacity');
insert into tblOrder (order_id, customer_id, source) values (181, 270, 'Customer-focused');
insert into tblOrder (order_id, customer_id, source) values (182, 711, 'data-warehouse');
insert into tblOrder (order_id, customer_id, source) values (183, 583, 'Face to face');
insert into tblOrder (order_id, customer_id, source) values (184, 63, 'human-resource');
insert into tblOrder (order_id, customer_id, source) values (185, 781, 'superstructure');
insert into tblOrder (order_id, customer_id, source) values (186, 26, 'Upgradable');
insert into tblOrder (order_id, customer_id, source) values (187, 139, 'Secured');
insert into tblOrder (order_id, customer_id, source) values (188, 78, 'circuit');
insert into tblOrder (order_id, customer_id, source) values (189, 364, 'Multi-lateral');
insert into tblOrder (order_id, customer_id, source) values (190, 831, 'flexibility');
insert into tblOrder (order_id, customer_id, source) values (191, 499, 'complexity');
insert into tblOrder (order_id, customer_id, source) values (192, 442, 'help-desk');
insert into tblOrder (order_id, customer_id, source) values (193, 698, 'focus group');
insert into tblOrder (order_id, customer_id, source) values (194, 177, 'infrastructure');
insert into tblOrder (order_id, customer_id, source) values (195, 566, 'forecast');
insert into tblOrder (order_id, customer_id, source) values (196, 287, 'Mandatory');
insert into tblOrder (order_id, customer_id, source) values (197, 717, 'De-engineered');
insert into tblOrder (order_id, customer_id, source) values (198, 898, '24 hour');
insert into tblOrder (order_id, customer_id, source) values (199, 936, 'parallelism');
insert into tblOrder (order_id, customer_id, source) values (200, 640, 'groupware');
insert into tblOrder (order_id, customer_id, source) values (201, 425, 'Quality-focused');
insert into tblOrder (order_id, customer_id, source) values (202, 861, 'conglomeration');
insert into tblOrder (order_id, customer_id, source) values (203, 783, 'User-centric');
insert into tblOrder (order_id, customer_id, source) values (204, 64, 'explicit');
insert into tblOrder (order_id, customer_id, source) values (205, 624, 'directional');
insert into tblOrder (order_id, customer_id, source) values (206, 462, 'Integrated');
insert into tblOrder (order_id, customer_id, source) values (207, 477, 'impactful');
insert into tblOrder (order_id, customer_id, source) values (208, 456, 'conglomeration');
insert into tblOrder (order_id, customer_id, source) values (209, 79, 'logistical');
insert into tblOrder (order_id, customer_id, source) values (210, 151, 'executive');
insert into tblOrder (order_id, customer_id, source) values (211, 482, 'Proactive');
insert into tblOrder (order_id, customer_id, source) values (212, 621, 'benchmark');
insert into tblOrder (order_id, customer_id, source) values (213, 577, 'Optimized');
insert into tblOrder (order_id, customer_id, source) values (214, 792, 'Synchronised');
insert into tblOrder (order_id, customer_id, source) values (215, 566, 'actuating');
insert into tblOrder (order_id, customer_id, source) values (216, 615, 'disintermediate');
insert into tblOrder (order_id, customer_id, source) values (217, 208, 'eco-centric');
insert into tblOrder (order_id, customer_id, source) values (218, 344, 'throughput');
insert into tblOrder (order_id, customer_id, source) values (219, 474, 'incremental');
insert into tblOrder (order_id, customer_id, source) values (220, 333, 'concept');
insert into tblOrder (order_id, customer_id, source) values (221, 228, 'Profound');
insert into tblOrder (order_id, customer_id, source) values (222, 652, 'orchestration');
insert into tblOrder (order_id, customer_id, source) values (223, 926, 'Team-oriented');
insert into tblOrder (order_id, customer_id, source) values (224, 98, 'superstructure');
insert into tblOrder (order_id, customer_id, source) values (225, 774, 'Sharable');
insert into tblOrder (order_id, customer_id, source) values (226, 245, 'attitude');
insert into tblOrder (order_id, customer_id, source) values (227, 646, 'archive');
insert into tblOrder (order_id, customer_id, source) values (228, 106, 'Right-sized');
insert into tblOrder (order_id, customer_id, source) values (229, 74, 'Down-sized');
insert into tblOrder (order_id, customer_id, source) values (230, 645, 'Configurable');
insert into tblOrder (order_id, customer_id, source) values (231, 221, 'context-sensitive');
insert into tblOrder (order_id, customer_id, source) values (232, 792, 'Cloned');
insert into tblOrder (order_id, customer_id, source) values (233, 77, '5th generation');
insert into tblOrder (order_id, customer_id, source) values (234, 250, 'empowering');
insert into tblOrder (order_id, customer_id, source) values (235, 582, 'toolset');
insert into tblOrder (order_id, customer_id, source) values (236, 262, 'secured line');
insert into tblOrder (order_id, customer_id, source) values (237, 704, 'uniform');
insert into tblOrder (order_id, customer_id, source) values (238, 85, 'radical');
insert into tblOrder (order_id, customer_id, source) values (239, 533, 'Persistent');
insert into tblOrder (order_id, customer_id, source) values (240, 996, 'Synergistic');
insert into tblOrder (order_id, customer_id, source) values (241, 708, 'middleware');
insert into tblOrder (order_id, customer_id, source) values (242, 828, 'eco-centric');
insert into tblOrder (order_id, customer_id, source) values (243, 519, 'portal');
insert into tblOrder (order_id, customer_id, source) values (244, 813, 'bifurcated');
insert into tblOrder (order_id, customer_id, source) values (245, 798, 'Networked');
insert into tblOrder (order_id, customer_id, source) values (246, 967, 'pricing structure');
insert into tblOrder (order_id, customer_id, source) values (247, 72, 'Persevering');
insert into tblOrder (order_id, customer_id, source) values (248, 760, 'Optimized');
insert into tblOrder (order_id, customer_id, source) values (249, 762, 'moratorium');
insert into tblOrder (order_id, customer_id, source) values (250, 14, 'context-sensitive');
insert into tblOrder (order_id, customer_id, source) values (251, 314, 'model');
insert into tblOrder (order_id, customer_id, source) values (252, 693, 'Decentralized');
insert into tblOrder (order_id, customer_id, source) values (253, 263, 'superstructure');
insert into tblOrder (order_id, customer_id, source) values (254, 9, 'Horizontal');
insert into tblOrder (order_id, customer_id, source) values (255, 982, 'array');
insert into tblOrder (order_id, customer_id, source) values (256, 830, 'Sharable');
insert into tblOrder (order_id, customer_id, source) values (257, 745, 'parallelism');
insert into tblOrder (order_id, customer_id, source) values (258, 727, 'Diverse');
insert into tblOrder (order_id, customer_id, source) values (259, 108, 'non-volatile');
insert into tblOrder (order_id, customer_id, source) values (260, 992, 'interface');
insert into tblOrder (order_id, customer_id, source) values (261, 962, 'next generation');
insert into tblOrder (order_id, customer_id, source) values (262, 528, 'software');
insert into tblOrder (order_id, customer_id, source) values (263, 753, 'contextually-based');
insert into tblOrder (order_id, customer_id, source) values (264, 99, 'Optional');
insert into tblOrder (order_id, customer_id, source) values (265, 773, 'dedicated');
insert into tblOrder (order_id, customer_id, source) values (266, 575, 'optimal');
insert into tblOrder (order_id, customer_id, source) values (267, 953, 'Team-oriented');
insert into tblOrder (order_id, customer_id, source) values (268, 597, 'portal');
insert into tblOrder (order_id, customer_id, source) values (269, 53, 'process improvement');
insert into tblOrder (order_id, customer_id, source) values (270, 898, 'Advanced');
insert into tblOrder (order_id, customer_id, source) values (271, 179, 'alliance');
insert into tblOrder (order_id, customer_id, source) values (272, 667, 'Virtual');
insert into tblOrder (order_id, customer_id, source) values (273, 601, 'attitude');
insert into tblOrder (order_id, customer_id, source) values (274, 724, 'Versatile');
insert into tblOrder (order_id, customer_id, source) values (275, 884, 'neutral');
insert into tblOrder (order_id, customer_id, source) values (276, 706, 'customer loyalty');
insert into tblOrder (order_id, customer_id, source) values (277, 184, 'encompassing');
insert into tblOrder (order_id, customer_id, source) values (278, 618, 'attitude-oriented');
insert into tblOrder (order_id, customer_id, source) values (279, 192, 'system engine');
insert into tblOrder (order_id, customer_id, source) values (280, 629, 'Assimilated');
insert into tblOrder (order_id, customer_id, source) values (281, 601, 'frame');
insert into tblOrder (order_id, customer_id, source) values (282, 145, 'pricing structure');
insert into tblOrder (order_id, customer_id, source) values (283, 770, 'Inverse');
insert into tblOrder (order_id, customer_id, source) values (284, 199, 'value-added');
insert into tblOrder (order_id, customer_id, source) values (285, 886, 'time-frame');
insert into tblOrder (order_id, customer_id, source) values (286, 265, 'zero administration');
insert into tblOrder (order_id, customer_id, source) values (287, 833, 'Compatible');
insert into tblOrder (order_id, customer_id, source) values (288, 884, 'Phased');
insert into tblOrder (order_id, customer_id, source) values (289, 140, 'encryption');
insert into tblOrder (order_id, customer_id, source) values (290, 534, 'Multi-lateral');
insert into tblOrder (order_id, customer_id, source) values (291, 165, 'architecture');
insert into tblOrder (order_id, customer_id, source) values (292, 429, 'Persistent');
insert into tblOrder (order_id, customer_id, source) values (293, 890, 'archive');
insert into tblOrder (order_id, customer_id, source) values (294, 558, 'needs-based');
insert into tblOrder (order_id, customer_id, source) values (295, 155, 'human-resource');
insert into tblOrder (order_id, customer_id, source) values (296, 359, 'hybrid');
insert into tblOrder (order_id, customer_id, source) values (297, 382, 'Robust');
insert into tblOrder (order_id, customer_id, source) values (298, 938, 'uniform');
insert into tblOrder (order_id, customer_id, source) values (299, 207, 'Open-architected');
insert into tblOrder (order_id, customer_id, source) values (300, 51, 'interactive');
insert into tblOrder (order_id, customer_id, source) values (301, 507, 'Virtual');
insert into tblOrder (order_id, customer_id, source) values (302, 56, 'Robust');
insert into tblOrder (order_id, customer_id, source) values (303, 51, 'Future-proofed');
insert into tblOrder (order_id, customer_id, source) values (304, 379, 'Switchable');
insert into tblOrder (order_id, customer_id, source) values (305, 134, 'bottom-line');
insert into tblOrder (order_id, customer_id, source) values (306, 803, 'value-added');
insert into tblOrder (order_id, customer_id, source) values (307, 155, 'Object-based');
insert into tblOrder (order_id, customer_id, source) values (308, 523, 'fault-tolerant');
insert into tblOrder (order_id, customer_id, source) values (309, 126, 'algorithm');
insert into tblOrder (order_id, customer_id, source) values (310, 878, 'homogeneous');
insert into tblOrder (order_id, customer_id, source) values (311, 292, 'interactive');
insert into tblOrder (order_id, customer_id, source) values (312, 793, 'user-facing');
insert into tblOrder (order_id, customer_id, source) values (313, 494, 'reciprocal');
insert into tblOrder (order_id, customer_id, source) values (314, 802, 'productivity');
insert into tblOrder (order_id, customer_id, source) values (315, 728, 'attitude');
insert into tblOrder (order_id, customer_id, source) values (316, 181, 'multi-state');
insert into tblOrder (order_id, customer_id, source) values (317, 710, 'neutral');
insert into tblOrder (order_id, customer_id, source) values (318, 231, 'software');
insert into tblOrder (order_id, customer_id, source) values (319, 900, 'hub');
insert into tblOrder (order_id, customer_id, source) values (320, 558, 'Virtual');
insert into tblOrder (order_id, customer_id, source) values (321, 812, 'Polarised');
insert into tblOrder (order_id, customer_id, source) values (322, 386, 'knowledge user');
insert into tblOrder (order_id, customer_id, source) values (323, 584, 'monitoring');
insert into tblOrder (order_id, customer_id, source) values (324, 364, 'Robust');
insert into tblOrder (order_id, customer_id, source) values (325, 665, 'structure');
insert into tblOrder (order_id, customer_id, source) values (326, 863, 'Profit-focused');
insert into tblOrder (order_id, customer_id, source) values (327, 666, 'interactive');
insert into tblOrder (order_id, customer_id, source) values (328, 514, 'Focused');
insert into tblOrder (order_id, customer_id, source) values (329, 991, 'Cloned');
insert into tblOrder (order_id, customer_id, source) values (330, 831, 'functionalities');
insert into tblOrder (order_id, customer_id, source) values (331, 3, '24/7');
insert into tblOrder (order_id, customer_id, source) values (332, 255, 'bandwidth-monitored');
insert into tblOrder (order_id, customer_id, source) values (333, 401, 'Ameliorated');
insert into tblOrder (order_id, customer_id, source) values (334, 259, 'high-level');
insert into tblOrder (order_id, customer_id, source) values (335, 491, 'Decentralized');
insert into tblOrder (order_id, customer_id, source) values (336, 158, 'extranet');
insert into tblOrder (order_id, customer_id, source) values (337, 505, 'workforce');
insert into tblOrder (order_id, customer_id, source) values (338, 557, 'strategy');
insert into tblOrder (order_id, customer_id, source) values (339, 980, 'bi-directional');
insert into tblOrder (order_id, customer_id, source) values (340, 164, 'architecture');
insert into tblOrder (order_id, customer_id, source) values (341, 303, 'methodical');
insert into tblOrder (order_id, customer_id, source) values (342, 219, 'flexibility');
insert into tblOrder (order_id, customer_id, source) values (343, 29, 'Devolved');
insert into tblOrder (order_id, customer_id, source) values (344, 253, 'Public-key');
insert into tblOrder (order_id, customer_id, source) values (345, 569, 'high-level');
insert into tblOrder (order_id, customer_id, source) values (346, 717, 'reciprocal');
insert into tblOrder (order_id, customer_id, source) values (347, 381, 'Reverse-engineered');
insert into tblOrder (order_id, customer_id, source) values (348, 202, 'didactic');
insert into tblOrder (order_id, customer_id, source) values (349, 819, 'optimizing');
insert into tblOrder (order_id, customer_id, source) values (350, 157, 'matrices');
insert into tblOrder (order_id, customer_id, source) values (351, 896, 'holistic');
insert into tblOrder (order_id, customer_id, source) values (352, 224, 'zero tolerance');
insert into tblOrder (order_id, customer_id, source) values (353, 649, 'intangible');
insert into tblOrder (order_id, customer_id, source) values (354, 361, 'Organized');
insert into tblOrder (order_id, customer_id, source) values (355, 737, 'explicit');
insert into tblOrder (order_id, customer_id, source) values (356, 768, 'Polarised');
insert into tblOrder (order_id, customer_id, source) values (357, 335, 'Programmable');
insert into tblOrder (order_id, customer_id, source) values (358, 387, 'superstructure');
insert into tblOrder (order_id, customer_id, source) values (359, 865, '24 hour');
insert into tblOrder (order_id, customer_id, source) values (360, 60, 'Focused');
insert into tblOrder (order_id, customer_id, source) values (361, 289, 'web-enabled');
insert into tblOrder (order_id, customer_id, source) values (362, 259, 'Customer-focused');
insert into tblOrder (order_id, customer_id, source) values (363, 952, 'secured line');
insert into tblOrder (order_id, customer_id, source) values (364, 836, 'system engine');
insert into tblOrder (order_id, customer_id, source) values (365, 637, 'Implemented');
insert into tblOrder (order_id, customer_id, source) values (366, 183, 'contingency');
insert into tblOrder (order_id, customer_id, source) values (367, 717, 'Synergistic');
insert into tblOrder (order_id, customer_id, source) values (368, 737, 'moderator');
insert into tblOrder (order_id, customer_id, source) values (369, 189, 'Enhanced');
insert into tblOrder (order_id, customer_id, source) values (370, 705, 'Pre-emptive');
insert into tblOrder (order_id, customer_id, source) values (371, 880, 'challenge');
insert into tblOrder (order_id, customer_id, source) values (372, 43, 'Profit-focused');
insert into tblOrder (order_id, customer_id, source) values (373, 574, 'interface');
insert into tblOrder (order_id, customer_id, source) values (374, 485, 'budgetary management');
insert into tblOrder (order_id, customer_id, source) values (375, 282, 'leverage');
insert into tblOrder (order_id, customer_id, source) values (376, 429, 'superstructure');
insert into tblOrder (order_id, customer_id, source) values (377, 991, 'encoding');
insert into tblOrder (order_id, customer_id, source) values (378, 411, 'client-driven');
insert into tblOrder (order_id, customer_id, source) values (379, 40, 'bifurcated');
insert into tblOrder (order_id, customer_id, source) values (380, 422, 'User-friendly');
insert into tblOrder (order_id, customer_id, source) values (381, 653, 'benchmark');
insert into tblOrder (order_id, customer_id, source) values (382, 459, 'Grass-roots');
insert into tblOrder (order_id, customer_id, source) values (383, 677, 'analyzer');
insert into tblOrder (order_id, customer_id, source) values (384, 520, 'Organic');
insert into tblOrder (order_id, customer_id, source) values (385, 618, 'regional');
insert into tblOrder (order_id, customer_id, source) values (386, 748, 'utilisation');
insert into tblOrder (order_id, customer_id, source) values (387, 571, 'synergy');
insert into tblOrder (order_id, customer_id, source) values (388, 479, 'Multi-lateral');
insert into tblOrder (order_id, customer_id, source) values (389, 239, 'directional');
insert into tblOrder (order_id, customer_id, source) values (390, 928, 'user-facing');
insert into tblOrder (order_id, customer_id, source) values (391, 765, 'zero defect');
insert into tblOrder (order_id, customer_id, source) values (392, 356, 'tangible');
insert into tblOrder (order_id, customer_id, source) values (393, 636, 'Realigned');
insert into tblOrder (order_id, customer_id, source) values (394, 32, 'tangible');
insert into tblOrder (order_id, customer_id, source) values (395, 565, 'middleware');
insert into tblOrder (order_id, customer_id, source) values (396, 121, 'content-based');
insert into tblOrder (order_id, customer_id, source) values (397, 426, 'middleware');
insert into tblOrder (order_id, customer_id, source) values (398, 493, 'help-desk');
insert into tblOrder (order_id, customer_id, source) values (399, 885, 'superstructure');
insert into tblOrder (order_id, customer_id, source) values (400, 251, 'Compatible');
insert into tblOrder (order_id, customer_id, source) values (401, 916, 'software');
insert into tblOrder (order_id, customer_id, source) values (402, 744, 'data-warehouse');
insert into tblOrder (order_id, customer_id, source) values (403, 24, 'Cloned');
insert into tblOrder (order_id, customer_id, source) values (404, 299, 'demand-driven');
insert into tblOrder (order_id, customer_id, source) values (405, 768, 'Networked');
insert into tblOrder (order_id, customer_id, source) values (406, 352, 'next generation');
insert into tblOrder (order_id, customer_id, source) values (407, 959, 'Enhanced');
insert into tblOrder (order_id, customer_id, source) values (408, 322, 'Grass-roots');
insert into tblOrder (order_id, customer_id, source) values (409, 885, 'Ameliorated');
insert into tblOrder (order_id, customer_id, source) values (410, 927, 'hardware');
insert into tblOrder (order_id, customer_id, source) values (411, 217, 'internet solution');
insert into tblOrder (order_id, customer_id, source) values (412, 438, 'eco-centric');
insert into tblOrder (order_id, customer_id, source) values (413, 118, 'logistical');
insert into tblOrder (order_id, customer_id, source) values (414, 661, 'regional');
insert into tblOrder (order_id, customer_id, source) values (415, 88, 'fault-tolerant');
insert into tblOrder (order_id, customer_id, source) values (416, 952, 'analyzer');
insert into tblOrder (order_id, customer_id, source) values (417, 6, 'Re-contextualized');
insert into tblOrder (order_id, customer_id, source) values (418, 814, 'framework');
insert into tblOrder (order_id, customer_id, source) values (419, 361, 'asynchronous');
insert into tblOrder (order_id, customer_id, source) values (420, 758, 'holistic');
insert into tblOrder (order_id, customer_id, source) values (421, 887, 'knowledge user');
insert into tblOrder (order_id, customer_id, source) values (422, 636, 'real-time');
insert into tblOrder (order_id, customer_id, source) values (423, 701, 'migration');
insert into tblOrder (order_id, customer_id, source) values (424, 36, 'Versatile');
insert into tblOrder (order_id, customer_id, source) values (425, 726, 'Fully-configurable');
insert into tblOrder (order_id, customer_id, source) values (426, 763, '5th generation');
insert into tblOrder (order_id, customer_id, source) values (427, 598, 'Down-sized');
insert into tblOrder (order_id, customer_id, source) values (428, 746, 'parallelism');
insert into tblOrder (order_id, customer_id, source) values (429, 418, 'actuating');
insert into tblOrder (order_id, customer_id, source) values (430, 508, 'artificial intelligence');
insert into tblOrder (order_id, customer_id, source) values (431, 421, 'client-server');
insert into tblOrder (order_id, customer_id, source) values (432, 316, 'instruction set');
insert into tblOrder (order_id, customer_id, source) values (433, 289, 'executive');
insert into tblOrder (order_id, customer_id, source) values (434, 247, 'algorithm');
insert into tblOrder (order_id, customer_id, source) values (435, 388, 'Optional');
insert into tblOrder (order_id, customer_id, source) values (436, 264, 'software');
insert into tblOrder (order_id, customer_id, source) values (437, 505, 'algorithm');
insert into tblOrder (order_id, customer_id, source) values (438, 622, 'policy');
insert into tblOrder (order_id, customer_id, source) values (439, 543, 'Innovative');
insert into tblOrder (order_id, customer_id, source) values (440, 18, 'ability');
insert into tblOrder (order_id, customer_id, source) values (441, 674, 'Automated');
insert into tblOrder (order_id, customer_id, source) values (442, 730, 'product');
insert into tblOrder (order_id, customer_id, source) values (443, 802, 'Networked');
insert into tblOrder (order_id, customer_id, source) values (444, 163, 'mobile');
insert into tblOrder (order_id, customer_id, source) values (445, 114, 'human-resource');
insert into tblOrder (order_id, customer_id, source) values (446, 75, 'Multi-channelled');
insert into tblOrder (order_id, customer_id, source) values (447, 851, 'Versatile');
insert into tblOrder (order_id, customer_id, source) values (448, 417, 'implementation');
insert into tblOrder (order_id, customer_id, source) values (449, 808, 'Automated');
insert into tblOrder (order_id, customer_id, source) values (450, 127, 'Enhanced');
insert into tblOrder (order_id, customer_id, source) values (451, 805, 'circuit');
insert into tblOrder (order_id, customer_id, source) values (452, 361, 'client-server');
insert into tblOrder (order_id, customer_id, source) values (453, 268, 'product');
insert into tblOrder (order_id, customer_id, source) values (454, 85, 'Proactive');
insert into tblOrder (order_id, customer_id, source) values (455, 670, 'optimal');
insert into tblOrder (order_id, customer_id, source) values (456, 641, 'Mandatory');
insert into tblOrder (order_id, customer_id, source) values (457, 211, 'fresh-thinking');
insert into tblOrder (order_id, customer_id, source) values (458, 493, 'Upgradable');
insert into tblOrder (order_id, customer_id, source) values (459, 623, 'multi-state');
insert into tblOrder (order_id, customer_id, source) values (460, 560, 'Virtual');
insert into tblOrder (order_id, customer_id, source) values (461, 187, 'forecast');
insert into tblOrder (order_id, customer_id, source) values (462, 89, 'secondary');
insert into tblOrder (order_id, customer_id, source) values (463, 342, 'mission-critical');
insert into tblOrder (order_id, customer_id, source) values (464, 789, 'instruction set');
insert into tblOrder (order_id, customer_id, source) values (465, 456, 'workforce');
insert into tblOrder (order_id, customer_id, source) values (466, 879, 'dedicated');
insert into tblOrder (order_id, customer_id, source) values (467, 399, 'scalable');
insert into tblOrder (order_id, customer_id, source) values (468, 9, 'object-oriented');
insert into tblOrder (order_id, customer_id, source) values (469, 365, '5th generation');
insert into tblOrder (order_id, customer_id, source) values (470, 292, 'instruction set');
insert into tblOrder (order_id, customer_id, source) values (471, 653, 'demand-driven');
insert into tblOrder (order_id, customer_id, source) values (472, 710, 'Multi-lateral');
insert into tblOrder (order_id, customer_id, source) values (473, 351, 'homogeneous');
insert into tblOrder (order_id, customer_id, source) values (474, 347, 'implementation');
insert into tblOrder (order_id, customer_id, source) values (475, 338, 'Automated');
insert into tblOrder (order_id, customer_id, source) values (476, 505, 'hardware');
insert into tblOrder (order_id, customer_id, source) values (477, 206, 'exuding');
insert into tblOrder (order_id, customer_id, source) values (478, 95, 'Object-based');
insert into tblOrder (order_id, customer_id, source) values (479, 852, 'holistic');
insert into tblOrder (order_id, customer_id, source) values (480, 666, 'software');
insert into tblOrder (order_id, customer_id, source) values (481, 113, 'Digitized');
insert into tblOrder (order_id, customer_id, source) values (482, 673, 'paradigm');
insert into tblOrder (order_id, customer_id, source) values (483, 783, 'optimizing');
insert into tblOrder (order_id, customer_id, source) values (484, 570, 'directional');
insert into tblOrder (order_id, customer_id, source) values (485, 645, 'system-worthy');
insert into tblOrder (order_id, customer_id, source) values (486, 192, 'workforce');
insert into tblOrder (order_id, customer_id, source) values (487, 771, 'bifurcated');
insert into tblOrder (order_id, customer_id, source) values (488, 998, 'architecture');
insert into tblOrder (order_id, customer_id, source) values (489, 441, 'local');
insert into tblOrder (order_id, customer_id, source) values (490, 931, 'focus group');
insert into tblOrder (order_id, customer_id, source) values (491, 205, 'Networked');
insert into tblOrder (order_id, customer_id, source) values (492, 817, 'website');
insert into tblOrder (order_id, customer_id, source) values (493, 312, 'Up-sized');
insert into tblOrder (order_id, customer_id, source) values (494, 503, 'Ergonomic');
insert into tblOrder (order_id, customer_id, source) values (495, 491, 'Vision-oriented');
insert into tblOrder (order_id, customer_id, source) values (496, 177, 'definition');
insert into tblOrder (order_id, customer_id, source) values (497, 449, 'capacity');
insert into tblOrder (order_id, customer_id, source) values (498, 276, 'Configurable');
insert into tblOrder (order_id, customer_id, source) values (499, 578, 'interface');
insert into tblOrder (order_id, customer_id, source) values (500, 855, 'Organic');
insert into tblOrder (order_id, customer_id, source) values (501, 607, 'well-modulated');
insert into tblOrder (order_id, customer_id, source) values (502, 967, 'cohesive');
insert into tblOrder (order_id, customer_id, source) values (503, 99, 'dedicated');
insert into tblOrder (order_id, customer_id, source) values (504, 37, 'Operative');
insert into tblOrder (order_id, customer_id, source) values (505, 531, 'empowering');
insert into tblOrder (order_id, customer_id, source) values (506, 748, 'Enhanced');
insert into tblOrder (order_id, customer_id, source) values (507, 518, 'didactic');
insert into tblOrder (order_id, customer_id, source) values (508, 848, 'encoding');
insert into tblOrder (order_id, customer_id, source) values (509, 549, 'service-desk');
insert into tblOrder (order_id, customer_id, source) values (510, 441, '24 hour');
insert into tblOrder (order_id, customer_id, source) values (511, 302, 'even-keeled');
insert into tblOrder (order_id, customer_id, source) values (512, 660, 'Total');
insert into tblOrder (order_id, customer_id, source) values (513, 49, 'Decentralized');
insert into tblOrder (order_id, customer_id, source) values (514, 352, 'policy');
insert into tblOrder (order_id, customer_id, source) values (515, 885, 'model');
insert into tblOrder (order_id, customer_id, source) values (516, 423, 'Managed');
insert into tblOrder (order_id, customer_id, source) values (517, 199, 'Monitored');
insert into tblOrder (order_id, customer_id, source) values (518, 875, 'directional');
insert into tblOrder (order_id, customer_id, source) values (519, 942, 'background');
insert into tblOrder (order_id, customer_id, source) values (520, 933, 'support');
insert into tblOrder (order_id, customer_id, source) values (521, 320, 'website');
insert into tblOrder (order_id, customer_id, source) values (522, 662, 'support');
insert into tblOrder (order_id, customer_id, source) values (523, 867, 'fault-tolerant');
insert into tblOrder (order_id, customer_id, source) values (524, 836, 'directional');
insert into tblOrder (order_id, customer_id, source) values (525, 914, 'attitude');
insert into tblOrder (order_id, customer_id, source) values (526, 765, 'project');
insert into tblOrder (order_id, customer_id, source) values (527, 701, 'intermediate');
insert into tblOrder (order_id, customer_id, source) values (528, 318, 'projection');
insert into tblOrder (order_id, customer_id, source) values (529, 685, 'Automated');
insert into tblOrder (order_id, customer_id, source) values (530, 422, 'Virtual');
insert into tblOrder (order_id, customer_id, source) values (531, 146, 'installation');
insert into tblOrder (order_id, customer_id, source) values (532, 627, 'customer loyalty');
insert into tblOrder (order_id, customer_id, source) values (533, 499, 'pricing structure');
insert into tblOrder (order_id, customer_id, source) values (534, 377, 'empowering');
insert into tblOrder (order_id, customer_id, source) values (535, 788, 'frame');
insert into tblOrder (order_id, customer_id, source) values (536, 159, 'Polarised');
insert into tblOrder (order_id, customer_id, source) values (537, 737, 'Exclusive');
insert into tblOrder (order_id, customer_id, source) values (538, 769, 'background');
insert into tblOrder (order_id, customer_id, source) values (539, 490, 'methodical');
insert into tblOrder (order_id, customer_id, source) values (540, 613, 'concept');
insert into tblOrder (order_id, customer_id, source) values (541, 16, 'architecture');
insert into tblOrder (order_id, customer_id, source) values (542, 507, '6th generation');
insert into tblOrder (order_id, customer_id, source) values (543, 628, 'grid-enabled');
insert into tblOrder (order_id, customer_id, source) values (544, 98, 'complexity');
insert into tblOrder (order_id, customer_id, source) values (545, 334, 'success');
insert into tblOrder (order_id, customer_id, source) values (546, 478, 'Digitized');
insert into tblOrder (order_id, customer_id, source) values (547, 933, 'function');
insert into tblOrder (order_id, customer_id, source) values (548, 252, 'architecture');
insert into tblOrder (order_id, customer_id, source) values (549, 540, 'Open-architected');
insert into tblOrder (order_id, customer_id, source) values (550, 521, 'scalable');
insert into tblOrder (order_id, customer_id, source) values (551, 700, 'access');
insert into tblOrder (order_id, customer_id, source) values (552, 224, 'demand-driven');
insert into tblOrder (order_id, customer_id, source) values (553, 690, 'next generation');
insert into tblOrder (order_id, customer_id, source) values (554, 535, 'initiative');
insert into tblOrder (order_id, customer_id, source) values (555, 368, 'Sharable');
insert into tblOrder (order_id, customer_id, source) values (556, 710, 'challenge');
insert into tblOrder (order_id, customer_id, source) values (557, 542, 'web-enabled');
insert into tblOrder (order_id, customer_id, source) values (558, 165, 'solution-oriented');
insert into tblOrder (order_id, customer_id, source) values (559, 140, 'strategy');
insert into tblOrder (order_id, customer_id, source) values (560, 538, 'Networked');
insert into tblOrder (order_id, customer_id, source) values (561, 214, 'attitude-oriented');
insert into tblOrder (order_id, customer_id, source) values (562, 65, 'infrastructure');
insert into tblOrder (order_id, customer_id, source) values (563, 97, 'motivating');
insert into tblOrder (order_id, customer_id, source) values (564, 565, 'neutral');
insert into tblOrder (order_id, customer_id, source) values (565, 20, '6th generation');
insert into tblOrder (order_id, customer_id, source) values (566, 927, 'workforce');
insert into tblOrder (order_id, customer_id, source) values (567, 248, 'structure');
insert into tblOrder (order_id, customer_id, source) values (568, 337, 'Monitored');
insert into tblOrder (order_id, customer_id, source) values (569, 623, 'Integrated');
insert into tblOrder (order_id, customer_id, source) values (570, 442, 'asymmetric');
insert into tblOrder (order_id, customer_id, source) values (571, 462, 'mobile');
insert into tblOrder (order_id, customer_id, source) values (572, 709, 'Phased');
insert into tblOrder (order_id, customer_id, source) values (573, 183, 'dedicated');
insert into tblOrder (order_id, customer_id, source) values (574, 932, 'Organized');
insert into tblOrder (order_id, customer_id, source) values (575, 502, '5th generation');
insert into tblOrder (order_id, customer_id, source) values (576, 894, 'Multi-tiered');
insert into tblOrder (order_id, customer_id, source) values (577, 302, 'Streamlined');
insert into tblOrder (order_id, customer_id, source) values (578, 896, 'adapter');
insert into tblOrder (order_id, customer_id, source) values (579, 386, 'Devolved');
insert into tblOrder (order_id, customer_id, source) values (580, 552, 'moderator');
insert into tblOrder (order_id, customer_id, source) values (581, 301, 'Inverse');
insert into tblOrder (order_id, customer_id, source) values (582, 608, 'incremental');
insert into tblOrder (order_id, customer_id, source) values (583, 338, 'Switchable');
insert into tblOrder (order_id, customer_id, source) values (584, 266, 'multimedia');
insert into tblOrder (order_id, customer_id, source) values (585, 709, 'contextually-based');
insert into tblOrder (order_id, customer_id, source) values (586, 393, 'Function-based');
insert into tblOrder (order_id, customer_id, source) values (587, 189, 'coherent');
insert into tblOrder (order_id, customer_id, source) values (588, 56, 'Fully-configurable');
insert into tblOrder (order_id, customer_id, source) values (589, 782, 'adapter');
insert into tblOrder (order_id, customer_id, source) values (590, 671, 'Open-source');
insert into tblOrder (order_id, customer_id, source) values (591, 806, 'Multi-layered');
insert into tblOrder (order_id, customer_id, source) values (592, 608, 'Business-focused');
insert into tblOrder (order_id, customer_id, source) values (593, 994, 'responsive');
insert into tblOrder (order_id, customer_id, source) values (594, 652, 'hybrid');
insert into tblOrder (order_id, customer_id, source) values (595, 500, 'eco-centric');
insert into tblOrder (order_id, customer_id, source) values (596, 596, 'Switchable');
insert into tblOrder (order_id, customer_id, source) values (597, 8, 'demand-driven');
insert into tblOrder (order_id, customer_id, source) values (598, 561, 'solution');
insert into tblOrder (order_id, customer_id, source) values (599, 133, 'Realigned');
insert into tblOrder (order_id, customer_id, source) values (600, 714, 'hybrid');
insert into tblOrder (order_id, customer_id, source) values (601, 483, 'Cross-platform');
insert into tblOrder (order_id, customer_id, source) values (602, 531, 'Polarised');
insert into tblOrder (order_id, customer_id, source) values (603, 338, 'success');
insert into tblOrder (order_id, customer_id, source) values (604, 478, 'groupware');
insert into tblOrder (order_id, customer_id, source) values (605, 861, 'algorithm');
insert into tblOrder (order_id, customer_id, source) values (606, 465, 'Multi-lateral');
insert into tblOrder (order_id, customer_id, source) values (607, 119, 'toolset');
insert into tblOrder (order_id, customer_id, source) values (608, 662, 'orchestration');
insert into tblOrder (order_id, customer_id, source) values (609, 509, 'leading edge');
insert into tblOrder (order_id, customer_id, source) values (610, 920, 'actuating');
insert into tblOrder (order_id, customer_id, source) values (611, 198, 'Optional');
insert into tblOrder (order_id, customer_id, source) values (612, 568, 'Inverse');
insert into tblOrder (order_id, customer_id, source) values (613, 350, 'logistical');
insert into tblOrder (order_id, customer_id, source) values (614, 511, 'benchmark');
insert into tblOrder (order_id, customer_id, source) values (615, 287, 'analyzing');
insert into tblOrder (order_id, customer_id, source) values (616, 684, 'discrete');
insert into tblOrder (order_id, customer_id, source) values (617, 639, 'Persistent');
insert into tblOrder (order_id, customer_id, source) values (618, 899, 'knowledge base');
insert into tblOrder (order_id, customer_id, source) values (619, 313, 'hybrid');
insert into tblOrder (order_id, customer_id, source) values (620, 250, 'cohesive');
insert into tblOrder (order_id, customer_id, source) values (621, 273, 'static');
insert into tblOrder (order_id, customer_id, source) values (622, 557, 'Digitized');
insert into tblOrder (order_id, customer_id, source) values (623, 27, 'Seamless');
insert into tblOrder (order_id, customer_id, source) values (624, 276, 'superstructure');
insert into tblOrder (order_id, customer_id, source) values (625, 561, 'info-mediaries');
insert into tblOrder (order_id, customer_id, source) values (626, 778, 'directional');
insert into tblOrder (order_id, customer_id, source) values (627, 808, 'focus group');
insert into tblOrder (order_id, customer_id, source) values (628, 447, 'Future-proofed');
insert into tblOrder (order_id, customer_id, source) values (629, 17, 'protocol');
insert into tblOrder (order_id, customer_id, source) values (630, 293, 'coherent');
insert into tblOrder (order_id, customer_id, source) values (631, 259, 'Graphical User Interface');
insert into tblOrder (order_id, customer_id, source) values (632, 60, 'multimedia');
insert into tblOrder (order_id, customer_id, source) values (633, 173, 'responsive');
insert into tblOrder (order_id, customer_id, source) values (634, 555, 'Front-line');
insert into tblOrder (order_id, customer_id, source) values (635, 735, 'Reactive');
insert into tblOrder (order_id, customer_id, source) values (636, 564, 'Enhanced');
insert into tblOrder (order_id, customer_id, source) values (637, 375, 'process improvement');
insert into tblOrder (order_id, customer_id, source) values (638, 434, 'explicit');
insert into tblOrder (order_id, customer_id, source) values (639, 786, 'Optional');
insert into tblOrder (order_id, customer_id, source) values (640, 97, 'Polarised');
insert into tblOrder (order_id, customer_id, source) values (641, 853, 'Devolved');
insert into tblOrder (order_id, customer_id, source) values (642, 470, 'Multi-tiered');
insert into tblOrder (order_id, customer_id, source) values (643, 425, 'Re-engineered');
insert into tblOrder (order_id, customer_id, source) values (644, 666, 'Realigned');
insert into tblOrder (order_id, customer_id, source) values (645, 720, 'Intuitive');
insert into tblOrder (order_id, customer_id, source) values (646, 860, 'Down-sized');
insert into tblOrder (order_id, customer_id, source) values (647, 313, 'Organic');
insert into tblOrder (order_id, customer_id, source) values (648, 596, 'alliance');
insert into tblOrder (order_id, customer_id, source) values (649, 487, 'motivating');
insert into tblOrder (order_id, customer_id, source) values (650, 493, 'exuding');
insert into tblOrder (order_id, customer_id, source) values (651, 748, 'utilisation');
insert into tblOrder (order_id, customer_id, source) values (652, 313, 'Implemented');
insert into tblOrder (order_id, customer_id, source) values (653, 165, 'Fundamental');
insert into tblOrder (order_id, customer_id, source) values (654, 694, 'hierarchy');
insert into tblOrder (order_id, customer_id, source) values (655, 614, 'discrete');
insert into tblOrder (order_id, customer_id, source) values (656, 262, 'encryption');
insert into tblOrder (order_id, customer_id, source) values (657, 502, 'context-sensitive');
insert into tblOrder (order_id, customer_id, source) values (658, 835, 'Business-focused');
insert into tblOrder (order_id, customer_id, source) values (659, 961, 'Business-focused');
insert into tblOrder (order_id, customer_id, source) values (660, 756, 'regional');
insert into tblOrder (order_id, customer_id, source) values (661, 882, 'capability');
insert into tblOrder (order_id, customer_id, source) values (662, 800, '24 hour');
insert into tblOrder (order_id, customer_id, source) values (663, 237, 'zero defect');
insert into tblOrder (order_id, customer_id, source) values (664, 549, 'array');
insert into tblOrder (order_id, customer_id, source) values (665, 349, 'Configurable');
insert into tblOrder (order_id, customer_id, source) values (666, 934, 'superstructure');
insert into tblOrder (order_id, customer_id, source) values (667, 726, 'Cross-platform');
insert into tblOrder (order_id, customer_id, source) values (668, 94, 'portal');
insert into tblOrder (order_id, customer_id, source) values (669, 623, 'value-added');
insert into tblOrder (order_id, customer_id, source) values (670, 686, 'Total');
insert into tblOrder (order_id, customer_id, source) values (671, 143, 'cohesive');
insert into tblOrder (order_id, customer_id, source) values (672, 766, 'national');
insert into tblOrder (order_id, customer_id, source) values (673, 522, 'Future-proofed');
insert into tblOrder (order_id, customer_id, source) values (674, 728, 'matrices');
insert into tblOrder (order_id, customer_id, source) values (675, 359, 'policy');
insert into tblOrder (order_id, customer_id, source) values (676, 483, 'Public-key');
insert into tblOrder (order_id, customer_id, source) values (677, 425, 'Enhanced');
insert into tblOrder (order_id, customer_id, source) values (678, 95, 'next generation');
insert into tblOrder (order_id, customer_id, source) values (679, 775, 'website');
insert into tblOrder (order_id, customer_id, source) values (680, 604, 'Digitized');
insert into tblOrder (order_id, customer_id, source) values (681, 635, 'systematic');
insert into tblOrder (order_id, customer_id, source) values (682, 511, 'neutral');
insert into tblOrder (order_id, customer_id, source) values (683, 676, 'transitional');
insert into tblOrder (order_id, customer_id, source) values (684, 113, 'Up-sized');
insert into tblOrder (order_id, customer_id, source) values (685, 999, 'Organized');
insert into tblOrder (order_id, customer_id, source) values (686, 904, 'grid-enabled');
insert into tblOrder (order_id, customer_id, source) values (687, 844, 'Triple-buffered');
insert into tblOrder (order_id, customer_id, source) values (688, 647, 'infrastructure');
insert into tblOrder (order_id, customer_id, source) values (689, 764, 'radical');
insert into tblOrder (order_id, customer_id, source) values (690, 614, 'service-desk');
insert into tblOrder (order_id, customer_id, source) values (691, 363, 'encoding');
insert into tblOrder (order_id, customer_id, source) values (692, 489, 'Versatile');
insert into tblOrder (order_id, customer_id, source) values (693, 892, 'collaboration');
insert into tblOrder (order_id, customer_id, source) values (694, 241, 'solution');
insert into tblOrder (order_id, customer_id, source) values (695, 561, 'access');
insert into tblOrder (order_id, customer_id, source) values (696, 610, 'Self-enabling');
insert into tblOrder (order_id, customer_id, source) values (697, 28, 'Realigned');
insert into tblOrder (order_id, customer_id, source) values (698, 360, 'local');
insert into tblOrder (order_id, customer_id, source) values (699, 433, 'utilisation');
insert into tblOrder (order_id, customer_id, source) values (700, 424, 'multimedia');
insert into tblOrder (order_id, customer_id, source) values (701, 688, 'directional');
insert into tblOrder (order_id, customer_id, source) values (702, 964, 'extranet');
insert into tblOrder (order_id, customer_id, source) values (703, 428, 'logistical');
insert into tblOrder (order_id, customer_id, source) values (704, 147, 'Enhanced');
insert into tblOrder (order_id, customer_id, source) values (705, 214, 'human-resource');
insert into tblOrder (order_id, customer_id, source) values (706, 149, 'moderator');
insert into tblOrder (order_id, customer_id, source) values (707, 632, 'Centralized');
insert into tblOrder (order_id, customer_id, source) values (708, 325, 'Face to face');
insert into tblOrder (order_id, customer_id, source) values (709, 67, 'Graphical User Interface');
insert into tblOrder (order_id, customer_id, source) values (710, 983, 'grid-enabled');
insert into tblOrder (order_id, customer_id, source) values (711, 493, 'User-friendly');
insert into tblOrder (order_id, customer_id, source) values (712, 366, '24/7');
insert into tblOrder (order_id, customer_id, source) values (713, 943, 'zero defect');
insert into tblOrder (order_id, customer_id, source) values (714, 587, 'synergy');
insert into tblOrder (order_id, customer_id, source) values (715, 638, 'heuristic');
insert into tblOrder (order_id, customer_id, source) values (716, 693, 'Decentralized');
insert into tblOrder (order_id, customer_id, source) values (717, 863, 'human-resource');
insert into tblOrder (order_id, customer_id, source) values (718, 911, 'leverage');
insert into tblOrder (order_id, customer_id, source) values (719, 459, 'even-keeled');
insert into tblOrder (order_id, customer_id, source) values (720, 924, 'Face to face');
insert into tblOrder (order_id, customer_id, source) values (721, 50, 'Switchable');
insert into tblOrder (order_id, customer_id, source) values (722, 297, 'Configurable');
insert into tblOrder (order_id, customer_id, source) values (723, 619, 'multimedia');
insert into tblOrder (order_id, customer_id, source) values (724, 800, 'Integrated');
insert into tblOrder (order_id, customer_id, source) values (725, 701, 'contingency');
insert into tblOrder (order_id, customer_id, source) values (726, 439, 'software');
insert into tblOrder (order_id, customer_id, source) values (727, 200, 'Managed');
insert into tblOrder (order_id, customer_id, source) values (728, 352, 'intranet');
insert into tblOrder (order_id, customer_id, source) values (729, 23, 'methodical');
insert into tblOrder (order_id, customer_id, source) values (730, 858, 'strategy');
insert into tblOrder (order_id, customer_id, source) values (731, 616, 'policy');
insert into tblOrder (order_id, customer_id, source) values (732, 767, 'analyzing');
insert into tblOrder (order_id, customer_id, source) values (733, 528, 'Grass-roots');
insert into tblOrder (order_id, customer_id, source) values (734, 522, 'next generation');
insert into tblOrder (order_id, customer_id, source) values (735, 716, 'Fundamental');
insert into tblOrder (order_id, customer_id, source) values (736, 402, 'software');
insert into tblOrder (order_id, customer_id, source) values (737, 500, 'system-worthy');
insert into tblOrder (order_id, customer_id, source) values (738, 623, 'Right-sized');
insert into tblOrder (order_id, customer_id, source) values (739, 788, 'Vision-oriented');
insert into tblOrder (order_id, customer_id, source) values (740, 134, 'uniform');
insert into tblOrder (order_id, customer_id, source) values (741, 822, 'attitude');
insert into tblOrder (order_id, customer_id, source) values (742, 734, 'Digitized');
insert into tblOrder (order_id, customer_id, source) values (743, 907, 'product');
insert into tblOrder (order_id, customer_id, source) values (744, 76, 'bottom-line');
insert into tblOrder (order_id, customer_id, source) values (745, 441, 'matrix');
insert into tblOrder (order_id, customer_id, source) values (746, 204, '5th generation');
insert into tblOrder (order_id, customer_id, source) values (747, 447, 'clear-thinking');
insert into tblOrder (order_id, customer_id, source) values (748, 332, 'zero tolerance');
insert into tblOrder (order_id, customer_id, source) values (749, 346, 'product');
insert into tblOrder (order_id, customer_id, source) values (750, 435, 'Function-based');
insert into tblOrder (order_id, customer_id, source) values (751, 481, 'Seamless');
insert into tblOrder (order_id, customer_id, source) values (752, 23, 'Digitized');
insert into tblOrder (order_id, customer_id, source) values (753, 130, 'monitoring');
insert into tblOrder (order_id, customer_id, source) values (754, 770, 'workforce');
insert into tblOrder (order_id, customer_id, source) values (755, 445, 'zero defect');
insert into tblOrder (order_id, customer_id, source) values (756, 490, 'Phased');
insert into tblOrder (order_id, customer_id, source) values (757, 965, 'Secured');
insert into tblOrder (order_id, customer_id, source) values (758, 341, 'Team-oriented');
insert into tblOrder (order_id, customer_id, source) values (759, 864, 'Re-engineered');
insert into tblOrder (order_id, customer_id, source) values (760, 623, 'Versatile');
insert into tblOrder (order_id, customer_id, source) values (761, 379, 'optimal');
insert into tblOrder (order_id, customer_id, source) values (762, 451, 'Customizable');
insert into tblOrder (order_id, customer_id, source) values (763, 799, 'Team-oriented');
insert into tblOrder (order_id, customer_id, source) values (764, 95, 'De-engineered');
insert into tblOrder (order_id, customer_id, source) values (765, 453, 'Fundamental');
insert into tblOrder (order_id, customer_id, source) values (766, 565, 'neutral');
insert into tblOrder (order_id, customer_id, source) values (767, 796, 'explicit');
insert into tblOrder (order_id, customer_id, source) values (768, 197, 'global');
insert into tblOrder (order_id, customer_id, source) values (769, 664, 'bottom-line');
insert into tblOrder (order_id, customer_id, source) values (770, 996, 'workforce');
insert into tblOrder (order_id, customer_id, source) values (771, 758, 'Fundamental');
insert into tblOrder (order_id, customer_id, source) values (772, 398, '5th generation');
insert into tblOrder (order_id, customer_id, source) values (773, 776, 'Fundamental');
insert into tblOrder (order_id, customer_id, source) values (774, 364, 'definition');
insert into tblOrder (order_id, customer_id, source) values (775, 689, 'leverage');
insert into tblOrder (order_id, customer_id, source) values (776, 809, 'Profit-focused');
insert into tblOrder (order_id, customer_id, source) values (777, 838, 'Triple-buffered');
insert into tblOrder (order_id, customer_id, source) values (778, 531, 'optimal');
insert into tblOrder (order_id, customer_id, source) values (779, 312, 'bifurcated');
insert into tblOrder (order_id, customer_id, source) values (780, 417, 'Extended');
insert into tblOrder (order_id, customer_id, source) values (781, 149, 'Front-line');
insert into tblOrder (order_id, customer_id, source) values (782, 949, 'moderator');
insert into tblOrder (order_id, customer_id, source) values (783, 103, 'empowering');
insert into tblOrder (order_id, customer_id, source) values (784, 777, 'open architecture');
insert into tblOrder (order_id, customer_id, source) values (785, 205, 'Diverse');
insert into tblOrder (order_id, customer_id, source) values (786, 363, '24 hour');
insert into tblOrder (order_id, customer_id, source) values (787, 56, 'Realigned');
insert into tblOrder (order_id, customer_id, source) values (788, 402, 'full-range');
insert into tblOrder (order_id, customer_id, source) values (789, 239, 'holistic');
insert into tblOrder (order_id, customer_id, source) values (790, 969, 'dynamic');
insert into tblOrder (order_id, customer_id, source) values (791, 86, 'bandwidth-monitored');
insert into tblOrder (order_id, customer_id, source) values (792, 575, 'benchmark');
insert into tblOrder (order_id, customer_id, source) values (793, 919, 'Integrated');
insert into tblOrder (order_id, customer_id, source) values (794, 104, 'Stand-alone');
insert into tblOrder (order_id, customer_id, source) values (795, 733, 'software');
insert into tblOrder (order_id, customer_id, source) values (796, 254, 'encoding');
insert into tblOrder (order_id, customer_id, source) values (797, 605, 'multi-state');
insert into tblOrder (order_id, customer_id, source) values (798, 143, 'fresh-thinking');
insert into tblOrder (order_id, customer_id, source) values (799, 911, 'definition');
insert into tblOrder (order_id, customer_id, source) values (800, 466, 'Future-proofed');
insert into tblOrder (order_id, customer_id, source) values (801, 671, 'Self-enabling');
insert into tblOrder (order_id, customer_id, source) values (802, 720, 'asynchronous');
insert into tblOrder (order_id, customer_id, source) values (803, 762, 'Enhanced');
insert into tblOrder (order_id, customer_id, source) values (804, 223, 'incremental');
insert into tblOrder (order_id, customer_id, source) values (805, 19, 'emulation');
insert into tblOrder (order_id, customer_id, source) values (806, 501, 'reciprocal');
insert into tblOrder (order_id, customer_id, source) values (807, 107, 'internet solution');
insert into tblOrder (order_id, customer_id, source) values (808, 705, 'multi-state');
insert into tblOrder (order_id, customer_id, source) values (809, 157, 'Switchable');
insert into tblOrder (order_id, customer_id, source) values (810, 299, 'cohesive');
insert into tblOrder (order_id, customer_id, source) values (811, 973, 'even-keeled');
insert into tblOrder (order_id, customer_id, source) values (812, 263, 'focus group');
insert into tblOrder (order_id, customer_id, source) values (813, 409, 'discrete');
insert into tblOrder (order_id, customer_id, source) values (814, 755, 'dynamic');
insert into tblOrder (order_id, customer_id, source) values (815, 395, 'flexibility');
insert into tblOrder (order_id, customer_id, source) values (816, 641, 'Reactive');
insert into tblOrder (order_id, customer_id, source) values (817, 743, 'protocol');
insert into tblOrder (order_id, customer_id, source) values (818, 614, '4th generation');
insert into tblOrder (order_id, customer_id, source) values (819, 756, 'encoding');
insert into tblOrder (order_id, customer_id, source) values (820, 747, 'Managed');
insert into tblOrder (order_id, customer_id, source) values (821, 771, 'exuding');
insert into tblOrder (order_id, customer_id, source) values (822, 433, 'Organic');
insert into tblOrder (order_id, customer_id, source) values (823, 190, 'Down-sized');
insert into tblOrder (order_id, customer_id, source) values (824, 148, 'Team-oriented');
insert into tblOrder (order_id, customer_id, source) values (825, 264, 'Synchronised');
insert into tblOrder (order_id, customer_id, source) values (826, 844, 'orchestration');
insert into tblOrder (order_id, customer_id, source) values (827, 116, '6th generation');
insert into tblOrder (order_id, customer_id, source) values (828, 784, 'Fundamental');
insert into tblOrder (order_id, customer_id, source) values (829, 872, 'Cross-platform');
insert into tblOrder (order_id, customer_id, source) values (830, 40, 'Programmable');
insert into tblOrder (order_id, customer_id, source) values (831, 946, 'real-time');
insert into tblOrder (order_id, customer_id, source) values (832, 822, 'well-modulated');
insert into tblOrder (order_id, customer_id, source) values (833, 652, 'Optional');
insert into tblOrder (order_id, customer_id, source) values (834, 65, 'Synergistic');
insert into tblOrder (order_id, customer_id, source) values (835, 536, 'client-server');
insert into tblOrder (order_id, customer_id, source) values (836, 661, 'neutral');
insert into tblOrder (order_id, customer_id, source) values (837, 530, 'Ergonomic');
insert into tblOrder (order_id, customer_id, source) values (838, 591, 'Reduced');
insert into tblOrder (order_id, customer_id, source) values (839, 737, 'Intuitive');
insert into tblOrder (order_id, customer_id, source) values (840, 934, 'dynamic');
insert into tblOrder (order_id, customer_id, source) values (841, 438, 'software');
insert into tblOrder (order_id, customer_id, source) values (842, 869, 'Mandatory');
insert into tblOrder (order_id, customer_id, source) values (843, 166, 'coherent');
insert into tblOrder (order_id, customer_id, source) values (844, 778, 'directional');
insert into tblOrder (order_id, customer_id, source) values (845, 138, 'optimal');
insert into tblOrder (order_id, customer_id, source) values (846, 984, 'service-desk');
insert into tblOrder (order_id, customer_id, source) values (847, 227, 'Organized');
insert into tblOrder (order_id, customer_id, source) values (848, 192, 'coherent');
insert into tblOrder (order_id, customer_id, source) values (849, 363, 'Optional');
insert into tblOrder (order_id, customer_id, source) values (850, 298, 'Virtual');
insert into tblOrder (order_id, customer_id, source) values (851, 227, 'asymmetric');
insert into tblOrder (order_id, customer_id, source) values (852, 119, 'Switchable');
insert into tblOrder (order_id, customer_id, source) values (853, 725, 'Down-sized');
insert into tblOrder (order_id, customer_id, source) values (854, 312, 'leading edge');
insert into tblOrder (order_id, customer_id, source) values (855, 89, 'attitude');
insert into tblOrder (order_id, customer_id, source) values (856, 3, 'emulation');
insert into tblOrder (order_id, customer_id, source) values (857, 565, 'Advanced');
insert into tblOrder (order_id, customer_id, source) values (858, 697, 'Object-based');
insert into tblOrder (order_id, customer_id, source) values (859, 866, 'scalable');
insert into tblOrder (order_id, customer_id, source) values (860, 576, 'interface');
insert into tblOrder (order_id, customer_id, source) values (861, 215, 'Synergistic');
insert into tblOrder (order_id, customer_id, source) values (862, 252, 'encompassing');
insert into tblOrder (order_id, customer_id, source) values (863, 4, 'data-warehouse');
insert into tblOrder (order_id, customer_id, source) values (864, 496, 'capability');
insert into tblOrder (order_id, customer_id, source) values (865, 477, 'open system');
insert into tblOrder (order_id, customer_id, source) values (866, 694, 'Progressive');
insert into tblOrder (order_id, customer_id, source) values (867, 939, 'analyzer');
insert into tblOrder (order_id, customer_id, source) values (868, 925, 'Re-contextualized');
insert into tblOrder (order_id, customer_id, source) values (869, 616, 'projection');
insert into tblOrder (order_id, customer_id, source) values (870, 192, 'Secured');
insert into tblOrder (order_id, customer_id, source) values (871, 222, 'web-enabled');
insert into tblOrder (order_id, customer_id, source) values (872, 520, 'Reduced');
insert into tblOrder (order_id, customer_id, source) values (873, 466, 'Realigned');
insert into tblOrder (order_id, customer_id, source) values (874, 319, 'Intuitive');
insert into tblOrder (order_id, customer_id, source) values (875, 502, 'Focused');
insert into tblOrder (order_id, customer_id, source) values (876, 965, 'function');
insert into tblOrder (order_id, customer_id, source) values (877, 603, 'Balanced');
insert into tblOrder (order_id, customer_id, source) values (878, 799, 'Up-sized');
insert into tblOrder (order_id, customer_id, source) values (879, 635, 'artificial intelligence');
insert into tblOrder (order_id, customer_id, source) values (880, 944, 'open architecture');
insert into tblOrder (order_id, customer_id, source) values (881, 158, 'Phased');
insert into tblOrder (order_id, customer_id, source) values (882, 562, 'cohesive');
insert into tblOrder (order_id, customer_id, source) values (883, 49, 'background');
insert into tblOrder (order_id, customer_id, source) values (884, 388, 'Graphical User Interface');
insert into tblOrder (order_id, customer_id, source) values (885, 240, 'circuit');
insert into tblOrder (order_id, customer_id, source) values (886, 337, 'eco-centric');
insert into tblOrder (order_id, customer_id, source) values (887, 459, 'Sharable');
insert into tblOrder (order_id, customer_id, source) values (888, 804, '24/7');
insert into tblOrder (order_id, customer_id, source) values (889, 829, 'customer loyalty');
insert into tblOrder (order_id, customer_id, source) values (890, 375, 'Function-based');
insert into tblOrder (order_id, customer_id, source) values (891, 305, 'Graphic Interface');
insert into tblOrder (order_id, customer_id, source) values (892, 166, 'well-modulated');
insert into tblOrder (order_id, customer_id, source) values (893, 486, 'functionalities');
insert into tblOrder (order_id, customer_id, source) values (894, 615, 'cohesive');
insert into tblOrder (order_id, customer_id, source) values (895, 977, 'software');
insert into tblOrder (order_id, customer_id, source) values (896, 147, 'analyzing');
insert into tblOrder (order_id, customer_id, source) values (897, 201, 'regional');
insert into tblOrder (order_id, customer_id, source) values (898, 61, 'directional');
insert into tblOrder (order_id, customer_id, source) values (899, 990, 'Proactive');
insert into tblOrder (order_id, customer_id, source) values (900, 773, 'Quality-focused');
insert into tblOrder (order_id, customer_id, source) values (901, 308, 'User-friendly');
insert into tblOrder (order_id, customer_id, source) values (902, 490, 'client-driven');
insert into tblOrder (order_id, customer_id, source) values (903, 888, 'Monitored');
insert into tblOrder (order_id, customer_id, source) values (904, 505, 'middleware');
insert into tblOrder (order_id, customer_id, source) values (905, 151, 'dedicated');
insert into tblOrder (order_id, customer_id, source) values (906, 989, 'knowledge user');
insert into tblOrder (order_id, customer_id, source) values (907, 481, 'background');
insert into tblOrder (order_id, customer_id, source) values (908, 439, 'Vision-oriented');
insert into tblOrder (order_id, customer_id, source) values (909, 598, 'intranet');
insert into tblOrder (order_id, customer_id, source) values (910, 37, 'Front-line');
insert into tblOrder (order_id, customer_id, source) values (911, 655, 'installation');
insert into tblOrder (order_id, customer_id, source) values (912, 22, 'core');
insert into tblOrder (order_id, customer_id, source) values (913, 70, 'Team-oriented');
insert into tblOrder (order_id, customer_id, source) values (914, 389, 'radical');
insert into tblOrder (order_id, customer_id, source) values (915, 474, 'leading edge');
insert into tblOrder (order_id, customer_id, source) values (916, 885, 'multi-state');
insert into tblOrder (order_id, customer_id, source) values (917, 643, 'user-facing');
insert into tblOrder (order_id, customer_id, source) values (918, 338, 'real-time');
insert into tblOrder (order_id, customer_id, source) values (919, 567, 'info-mediaries');
insert into tblOrder (order_id, customer_id, source) values (920, 251, 'Implemented');
insert into tblOrder (order_id, customer_id, source) values (921, 332, 'matrix');
insert into tblOrder (order_id, customer_id, source) values (922, 978, 'attitude-oriented');
insert into tblOrder (order_id, customer_id, source) values (923, 409, 'composite');
insert into tblOrder (order_id, customer_id, source) values (924, 146, 'tangible');
insert into tblOrder (order_id, customer_id, source) values (925, 492, 'optimal');
insert into tblOrder (order_id, customer_id, source) values (926, 228, 'functionalities');
insert into tblOrder (order_id, customer_id, source) values (927, 740, 'Vision-oriented');
insert into tblOrder (order_id, customer_id, source) values (928, 840, 'leading edge');
insert into tblOrder (order_id, customer_id, source) values (929, 134, 'Phased');
insert into tblOrder (order_id, customer_id, source) values (930, 658, 'Adaptive');
insert into tblOrder (order_id, customer_id, source) values (931, 72, 'dedicated');
insert into tblOrder (order_id, customer_id, source) values (932, 408, 'product');
insert into tblOrder (order_id, customer_id, source) values (933, 93, 'intranet');
insert into tblOrder (order_id, customer_id, source) values (934, 888, 'migration');
insert into tblOrder (order_id, customer_id, source) values (935, 287, 'synergy');
insert into tblOrder (order_id, customer_id, source) values (936, 25, 'methodical');
insert into tblOrder (order_id, customer_id, source) values (937, 334, 'value-added');
insert into tblOrder (order_id, customer_id, source) values (938, 782, 'access');
insert into tblOrder (order_id, customer_id, source) values (939, 327, 'Vision-oriented');
insert into tblOrder (order_id, customer_id, source) values (940, 446, 'transitional');
insert into tblOrder (order_id, customer_id, source) values (941, 134, 'internet solution');
insert into tblOrder (order_id, customer_id, source) values (942, 776, 'superstructure');
insert into tblOrder (order_id, customer_id, source) values (943, 953, 'Enhanced');
insert into tblOrder (order_id, customer_id, source) values (944, 798, 'Robust');
insert into tblOrder (order_id, customer_id, source) values (945, 656, 'methodical');
insert into tblOrder (order_id, customer_id, source) values (946, 980, 'eco-centric');
insert into tblOrder (order_id, customer_id, source) values (947, 783, 'Face to face');
insert into tblOrder (order_id, customer_id, source) values (948, 471, 'core');
insert into tblOrder (order_id, customer_id, source) values (949, 492, 'Open-source');
insert into tblOrder (order_id, customer_id, source) values (950, 677, 'Ameliorated');
insert into tblOrder (order_id, customer_id, source) values (951, 618, 'algorithm');
insert into tblOrder (order_id, customer_id, source) values (952, 743, 'Multi-lateral');
insert into tblOrder (order_id, customer_id, source) values (953, 565, 'Upgradable');
insert into tblOrder (order_id, customer_id, source) values (954, 608, 'data-warehouse');
insert into tblOrder (order_id, customer_id, source) values (955, 20, 'radical');
insert into tblOrder (order_id, customer_id, source) values (956, 72, 'uniform');
insert into tblOrder (order_id, customer_id, source) values (957, 904, 'software');
insert into tblOrder (order_id, customer_id, source) values (958, 905, 'paradigm');
insert into tblOrder (order_id, customer_id, source) values (959, 615, 'high-level');
insert into tblOrder (order_id, customer_id, source) values (960, 416, 'knowledge user');
insert into tblOrder (order_id, customer_id, source) values (961, 837, 'Streamlined');
insert into tblOrder (order_id, customer_id, source) values (962, 684, 'Streamlined');
insert into tblOrder (order_id, customer_id, source) values (963, 213, 'time-frame');
insert into tblOrder (order_id, customer_id, source) values (964, 381, 'extranet');
insert into tblOrder (order_id, customer_id, source) values (965, 248, 'open system');
insert into tblOrder (order_id, customer_id, source) values (966, 638, 'interface');
insert into tblOrder (order_id, customer_id, source) values (967, 87, 'Graphic Interface');
insert into tblOrder (order_id, customer_id, source) values (968, 365, 'Distributed');
insert into tblOrder (order_id, customer_id, source) values (969, 86, 'attitude');
insert into tblOrder (order_id, customer_id, source) values (970, 937, 'Vision-oriented');
insert into tblOrder (order_id, customer_id, source) values (971, 45, 'Down-sized');
insert into tblOrder (order_id, customer_id, source) values (972, 134, 'Face to face');
insert into tblOrder (order_id, customer_id, source) values (973, 522, 'content-based');
insert into tblOrder (order_id, customer_id, source) values (974, 592, 'task-force');
insert into tblOrder (order_id, customer_id, source) values (975, 180, 'software');
insert into tblOrder (order_id, customer_id, source) values (976, 420, 'Mandatory');
insert into tblOrder (order_id, customer_id, source) values (977, 865, 'strategy');
insert into tblOrder (order_id, customer_id, source) values (978, 282, 'dedicated');
insert into tblOrder (order_id, customer_id, source) values (979, 755, 'Extended');
insert into tblOrder (order_id, customer_id, source) values (980, 713, 'installation');
insert into tblOrder (order_id, customer_id, source) values (981, 399, 'throughput');
insert into tblOrder (order_id, customer_id, source) values (982, 47, 'Secured');
insert into tblOrder (order_id, customer_id, source) values (983, 306, 'support');
insert into tblOrder (order_id, customer_id, source) values (984, 397, 'attitude-oriented');
insert into tblOrder (order_id, customer_id, source) values (985, 621, 'middleware');
insert into tblOrder (order_id, customer_id, source) values (986, 279, 'Mandatory');
insert into tblOrder (order_id, customer_id, source) values (987, 909, 'collaboration');
insert into tblOrder (order_id, customer_id, source) values (988, 243, 'matrix');
insert into tblOrder (order_id, customer_id, source) values (989, 698, 'infrastructure');
insert into tblOrder (order_id, customer_id, source) values (990, 915, 'didactic');
insert into tblOrder (order_id, customer_id, source) values (991, 314, 'well-modulated');
insert into tblOrder (order_id, customer_id, source) values (992, 902, 'Decentralized');
insert into tblOrder (order_id, customer_id, source) values (993, 136, 'executive');
insert into tblOrder (order_id, customer_id, source) values (994, 822, 'uniform');
insert into tblOrder (order_id, customer_id, source) values (995, 692, '5th generation');
insert into tblOrder (order_id, customer_id, source) values (996, 337, 'disintermediate');
insert into tblOrder (order_id, customer_id, source) values (997, 780, 'moratorium');
insert into tblOrder (order_id, customer_id, source) values (998, 407, 'flexibility');
insert into tblOrder (order_id, customer_id, source) values (999, 293, 'task-force');
insert into tblOrder (order_id, customer_id, source) values (1000, 36, 'dedicated');
