DROP TABLE IF EXISTS tblProducts CASCADE;

create table tblProducts (
	product_id SERIAL PRIMARY KEY,
	isbn CHAR(11),
	product_name VARCHAR(100),
	author VARCHAR(30),
	genre VARCHAR(20),
	publisher VARCHAR(20),
	product_type INTEGER,
	description VARCHAR(200)
);
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('147492343-7', 'Fundamentals of Wavelets', 'Goswami, Jaideva', 'signal_processing', 'Wiley', 2, 'Badger, european');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('347134497-7', 'Data Smart', 'Foreman, John', 'data_science', 'Wiley', 2, 'Capuchin, brown');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('825681833-6', 'God Created the Integers', 'Hawking, Stephen', 'mathematics', 'Penguin', 2, 'Hippopotamus');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('032125405-8', 'Superfreakonomics', 'Dubner, Stephen', 'economics', 'HarperCollins', 2, 'Brown brocket');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('275909620-3', 'Orientalism', 'Said, Edward', 'history', 'Penguin', 1, 'Peccary, white-lipped');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('266783088-1', 'Nature of Statistical Learning Theory, The', 'Vapnik, Vladimir', 'data_science', 'Springer', 2, 'Tiger cat');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('796068558-4', 'Integration of the Indian States', 'Menon, V P', 'history', 'Orient Blackswan', 2, 'Galah');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('248433300-5', 'Drunkard''s Walk, The', 'Mlodinow, Leonard', 'science', 'Penguin', 1, 'White-browed owl');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('269453184-9', 'Image Processing & Mathematical Morphology', 'Shih, Frank', 'signal_processing', 'CRC', 1, 'Baboon, chacma');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('881300662-4', 'How to Think Like Sherlock Holmes', 'Konnikova, Maria', 'psychology', 'Penguin', 2, 'Savanna fox');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('661264940-2', 'Data Scientists at Work', 'Sebastian Gutierrez', 'data_science', 'Apress', 1, 'Cormorant, king');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('903580343-4', 'Slaughterhouse Five', 'Vonnegut, Kurt', 'fiction', 'Random House', 2, 'Carpet python');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('081414313-X', 'Birth of a Theorem', 'Villani, Cedric', 'mathematics', 'Bodley Head', 1, 'Sheep, red');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('923281848-5', 'Structure & Interpretation of Computer Programs', 'Sussman, Gerald', 'computer_science', 'MIT Press', 2, 'Phalarope, red');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('146978427-0', 'Age of Wrath, The', 'Eraly, Abraham', 'history', 'Penguin', 1, 'Egret, cattle');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('598516422-5', 'Trial, The', 'Kafka, Frank', 'fiction', 'Random House', 2, 'Anaconda (unidentified)');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('201257219-7', 'Statistical Decision Theory''', 'Pratt, John', 'data_science', 'MIT Press', 1, 'Egret, snowy');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('207240514-9', 'Data Mining Handbook', 'Nisbet, Robert', 'data_science', 'Apress', 2, 'Dragon, asian water');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('490234908-6', 'New Machiavelli, The', 'Wells, H. G.', 'fiction', 'Penguin', 1, 'Mongoose, yellow');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('154234031-4', 'Physics & Philosophy', 'Heisenberg, Werner', 'science', 'Penguin', 1, 'Lesser masked weaver');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('596231032-2', 'Making Software', 'Oram, Andy', 'computer_science', 'O''Reilly', 1, 'Golden eagle');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('964704830-0', 'Analysis, Vol I', 'Tao, Terence', 'mathematics', 'HBA', 1, 'Southern lapwing');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('380661229-3', 'Machine Learning for Hackers', 'Conway, Drew', 'data_science', 'O''Reilly', 2, 'Kangaroo, western grey');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('910747098-3', 'Signal and the Noise, The', 'Silver, Nate', 'data_science', 'Penguin', 2, 'Dove, galapagos');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('269009249-2', 'Python for Data Analysis', 'McKinney, Wes', 'data_science', 'O''Reilly', 2, 'Gull, southern black-backed');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('523909302-4', 'Introduction to Algorithms', 'Cormen, Thomas', 'computer_science', 'MIT Press', 2, 'Chickadee, black-capped');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('795199519-3', 'Beautiful and the Damned, The', 'Deb, Siddhartha', 'nonfiction', 'Penguin', 2, 'Giant otter');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('421494481-X', 'Outsider, The', 'Camus, Albert', 'fiction', 'Penguin', 2, 'Monitor, two-banded');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('420442058-3', 'Complete Sherlock Holmes, The - Vol I', 'Doyle, Arthur Conan', 'fiction', 'Random House', 2, 'Richardson''s ground squirrel');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('930145608-7', 'Complete Sherlock Holmes, The - Vol II', 'Doyle, Arthur Conan', 'fiction', 'Random House', 2, 'Western lowland gorilla');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('778636714-4', 'Wealth of Nations, The', 'Smith, Adam', 'economics', 'Random House', 2, 'White-throated kingfisher');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('657248585-4', 'Pillars of the Earth, The', 'Follett, Ken', 'fiction', 'Random House', 1, 'Desert kangaroo rat');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('013738599-4', 'Mein Kampf', 'Hitler, Adolf', 'nonfiction', 'Rupa', 2, 'Badger, eurasian');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('151132975-0', 'Tao of Physics, The', 'Capra, Fritjof', 'science', 'Penguin', 1, 'Macaw, red and blue');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('467501473-9', 'Surely You''re Joking Mr Feynman', 'Feynman, Richard', 'science', 'Random House', 2, 'African skink');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('757657006-7', 'Farewell to Arms, A', 'Hemingway, Ernest', 'fiction', 'Rupa', 2, 'Indian peacock');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('180418250-8', 'Veteran, The', 'Forsyth, Frederick', 'fiction', 'Transworld', 1, 'Warthog');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('687979826-8', 'False Impressions', 'Archer, Jeffery', 'fiction', 'Pan', 2, 'Mynah, indian');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('754894664-3', 'Last Lecture, The', 'Pausch, Randy', 'nonfiction', 'Hyperion', 1, 'Zebra, common');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('552594925-3', 'Return of the Primitive', 'Rand, Ayn', 'philosophy', 'Penguin', 2, 'Black curlew');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('720933488-2', 'Jurassic Park', 'Crichton, Michael', 'fiction', 'Random House', 2, 'Indian tree pie');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('875663409-9', 'Russian Journal, A', 'Steinbeck, John', 'nonfiction', 'Penguin', 2, 'Woodpecker, red-headed');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('245571468-3', 'Tales of Mystery and Imagination', 'Poe, Edgar Allen', 'fiction', 'HarperCollins', 2, 'Capuchin, brown');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('347942628-X', 'Freakonomics', 'Dubner, Stephen', 'economics', 'Penguin', 2, 'Black-crowned crane');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('563251176-6', 'Hidden Connections, The', 'Capra, Fritjof', 'science', 'HarperCollins', 2, 'Deer, swamp');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('956411057-2', 'Story of Philosophy, The', 'Durant, Will', 'philosophy', 'Pocket', 2, 'Racer, american');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('553706525-8', 'Asami Asami', 'Deshpande, P L', 'fiction', 'Mauj', 1, 'Wagtail, african pied');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('724024553-5', 'Journal of a Novel', 'Steinbeck, John', 'fiction', 'Penguin', 2, 'Reedbuck, bohor');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('965300438-7', 'Once There Was a War', 'Steinbeck, John', 'nonfiction', 'Penguin', 1, 'Western patch-nosed snake');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('190305536-9', 'Moon is Down, The', 'Steinbeck, John', 'fiction', 'Penguin', 2, 'Common mynah');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('175093902-9', 'Brethren, The', 'Grisham, John', 'fiction', 'Random House', 2, 'Campo flicker');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('180269372-6', 'In a Free State', 'Naipaul, V. S.', 'fiction', 'Rupa', 1, 'Sea birds (unidentified)');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('662657274-1', 'Catch 22', 'Heller, Joseph', 'fiction', 'Random House', 2, 'Vulture, bengal');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('181796411-9', 'Complete Mastermind, The', 'BBC', 'nonfiction', 'BBC', 2, 'Wagtail, african pied');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('301272519-9', 'Dylan on Dylan', 'Dylan, Bob', 'nonfiction', 'Random House', 2, 'Squirrel, indian giant');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('303919625-1', 'Soft Computing & Intelligent Systems', 'Gupta, Madan', 'data_science', 'Elsevier', 1, 'Lemur, brown');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('637830394-0', 'Textbook of Economic Theory', 'Stonier, Alfred', 'economics', 'Pearson', 2, 'Sparrow, house');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('872123623-2', 'Econometric Analysis', 'Greene, W. H.', 'economics', 'Pearson', 2, 'Oryx, fringe-eared');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('389039420-5', 'Learning OpenCV', 'Bradsky, Gary', 'data_science', 'O''Reilly', 1, 'Bee-eater (unidentified)');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('805265323-1', 'Data Structures Using C & C++', 'Tanenbaum, Andrew', 'computer_science', 'Prentice Hall', 1, 'Partridge, coqui');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('566164141-9', 'Computer Vision, A Modern Approach', 'Forsyth, David', 'data_science', 'Pearson', 2, 'Dove, mourning collared');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('157505578-3', 'Principles of Communication Systems', 'Taub, Schilling', 'computer_science', 'TMH', 2, 'Hyrax');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('766367964-4', 'Let Us C', 'Kanetkar, Yashwant', 'computer_science', 'Prentice Hall', 1, 'Vulture, oriental white-backed');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('162609871-9', 'Amulet of Samarkand, The', 'Stroud, Jonathan', 'fiction', 'Random House', 2, 'Macaw, green-winged');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('748200070-4', 'Crime and Punishment', 'Dostoevsky, Fyodor', 'fiction', 'Penguin', 2, 'Bird, magnificent frigate');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('708412318-0', 'Angels & Demons', 'Brown, Dan', 'fiction', 'Random House', 2, 'European stork');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('745151645-8', 'Argumentative Indian, The', 'Sen, Amartya', 'nonfiction', 'Picador', 2, 'Mongoose, yellow');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('564447757-6', 'Sea of Poppies', 'Ghosh, Amitav', 'fiction', 'Penguin', 2, 'Sheathbill, snowy');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('868785895-7', 'Idea of Justice, The', 'Sen, Amartya', 'nonfiction', 'Penguin', 2, 'Comb duck');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('733450062-8', 'Raisin in the Sun, A', 'Hansberry, Lorraine', 'fiction', 'Penguin', 2, 'Giant girdled lizard');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('212515662-8', 'All the President''s Men', 'Woodward, Bob', 'history', 'Random House', 2, 'Blacksmith plover');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('937877842-9', 'Prisoner of Birth, A', 'Archer, Jeffery', 'fiction', 'Pan', 2, 'African lion');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('568759515-5', 'Scoop!', 'Nayar, Kuldip', 'history', 'HarperCollins', 1, 'Ibis, glossy');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('158909477-8', 'Ahe Manohar Tari', 'Deshpande, Sunita', 'nonfiction', 'Mauj', 2, 'Crake, african black');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('972546590-3', 'Last Mughal, The', 'Dalrymple, William', 'history', 'Penguin', 2, 'Albatross, galapagos');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('852965765-9', 'Social Choice & Welfare, Vol 39 No. 1', 'Various', 'economics', 'Springer', 2, 'Langur, hanuman');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('121057590-6', 'Radiowaril Bhashane & Shrutika', 'Deshpande, P L', 'nonfiction', 'Mauj', 1, 'Crane, blue');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('336499902-3', 'Gun Gayin Awadi', 'Deshpande, P L', 'nonfiction', 'Mauj', 1, 'Hornbill, leadbeateri''s ground');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('270924861-1', 'Aghal Paghal', 'Deshpande, P L', 'nonfiction', 'Mauj', 2, 'Colobus, white-mantled');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('393582912-4', 'Maqta-e-Ghalib', 'Garg, Sanjay', 'fiction', 'Mauj', 2, 'Water moccasin');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('766214927-7', 'Beyond Degrees', null, 'nonfiction', 'HarperCollins', 2, 'Buffalo, american');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('187174126-2', 'Manasa', 'Kale, V P', 'nonfiction', 'Mauj', 2, 'Monitor, two-banded');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('576186497-5', 'India from Midnight to Milennium', 'Tharoor, Shashi', 'history', 'Penguin', 1, 'Gonolek, burchell''s');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('834583525-2', 'World''s Greatest Trials, The', null, 'history', null, 2, 'Oryx, fringe-eared');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('898224881-1', 'Great Indian Novel, The', 'Tharoor, Shashi', 'fiction', 'Penguin', 2, 'Cow, scottish highland');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('973589482-3', 'O Jerusalem!', 'Lapierre, Dominique', 'history', 'vikas', 1, 'Colobus, white-mantled');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('753921872-X', 'City of Joy, The', 'Lapierre, Dominique', 'fiction', 'vikas', 2, 'Peccary, white-lipped');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('836560105-2', 'Freedom at Midnight', 'Lapierre, Dominique', 'history', 'vikas', 2, 'Sungazer, yellow-brown');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('532661746-3', 'Winter of Our Discontent, The', 'Steinbeck, John', 'fiction', 'Penguin', 1, 'Tammar wallaby');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('619781408-0', 'On Education', 'Russell, Bertrand', 'philosophy', 'Routledge', 1, 'Caracal');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('060332112-7', 'Free Will', 'Harris, Sam', 'philosophy', 'FreePress', 2, 'Egyptian cobra');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('943259765-2', 'Bookless in Baghdad', 'Tharoor, Shashi', 'nonfiction', 'Penguin', 2, 'Stork, european');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('919178682-7', 'Case of the Lame Canary, The', 'Gardner, Earle Stanley', 'fiction', null, 1, 'Purple grenadier');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('074429549-1', 'Theory of Everything, The', 'Hawking, Stephen', 'science', 'Jaico', 1, 'Mourning collared dove');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('505732893-X', 'New Markets & Other Essays', 'Drucker, Peter', 'economics', 'Penguin', 1, 'South American puma');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('596033928-5', 'Electric Universe', 'Bodanis, David', 'science', 'Penguin', 2, 'Dog, bush');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('303012740-0', 'Hunchback of Notre Dame, The', 'Hugo, Victor', 'fiction', 'Random House', 1, 'Bent-toed gecko');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('587267378-7', 'Burning Bright', 'Steinbeck, John', 'fiction', 'Penguin', 1, 'Cape Barren goose');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('569953571-3', 'Age of Discontuinity, The', 'Drucker, Peter', 'economics', 'Random House', 2, 'Deer, spotted');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('434971280-1', 'Doctor in the Nude', 'Gordon, Richard', 'fiction', 'Penguin', 1, 'Golden-mantled ground squirrel');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('298755544-X', 'Down and Out in Paris & London', 'Orwell, George', 'nonfiction', 'Penguin', 2, 'Fox, cape');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('726952872-1', 'Identity & Violence', 'Sen, Amartya', 'philosophy', 'Penguin', 2, 'Spur-winged goose');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('317269724-X', 'Beyond the Three Seas', 'Dalrymple, William', 'history', 'Random House', 2, 'Booby, masked');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('602031674-2', 'World''s Greatest Short Stories, The', null, 'fiction', 'Jaico', 2, 'Mourning collared dove');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('736031093-8', 'Talking Straight', 'Iacoca, Lee', 'nonfiction', null, 2, 'Galapagos mockingbird');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('073328785-9', 'Maugham''s Collected Short Stories, Vol 3', 'Maugham, William S', 'fiction', 'Vintage', 1, 'White-winged dove');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('901022001-X', 'Phantom of Manhattan, The', 'Forsyth, Frederick', 'fiction', null, 1, 'Squirrel glider');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('997768514-2', 'Ashenden of The British Agent', 'Maugham, William S', 'fiction', 'Vintage', 2, 'Goose, greylag');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('039154403-9', 'Zen & The Art of Motorcycle Maintenance', 'Pirsig, Robert', 'philosophy', 'Vintage', 2, 'Blue wildebeest');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('148726917-X', 'Great War for Civilization, The', 'Fisk, Robert', 'history', 'HarperCollins', 2, 'Common genet');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('593661280-5', 'We the Living', 'Rand, Ayn', 'fiction', 'Penguin', 1, 'Dove, white-winged');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('642531691-8', 'Artist and the Mathematician, The', 'Aczel, Amir', 'science', 'HighStakes', 2, 'Kangaroo, red');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('590346455-6', 'History of Western Philosophy', 'Russell, Bertrand', 'philosophy', 'Routledge', 1, 'Goose, canada');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('283309156-7', 'Selected Short Stories', null, 'fiction', 'Jaico', 2, 'Cockatoo, red-breasted');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('888479330-0', 'Rationality & Freedom', 'Sen, Amartya', 'economics', 'Springer', 1, 'Heron, little');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('034216028-1', 'Clash of Civilizations and Remaking of the World Order', 'Huntington, Samuel', 'history', 'Simon&Schuster', 2, 'Mynah, common');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('859803775-3', 'Uncommon Wisdom', 'Capra, Fritjof', 'nonfiction', 'Fontana', 2, 'Anaconda (unidentified)');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('683242265-2', 'One', 'Bach, Richard', 'nonfiction', 'Dell', 2, 'Macaque, rhesus');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('981155465-X', 'Karl Marx Biography', null, 'nonfiction', null, 2, 'Savanna fox');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('204222144-9', 'To Sir With Love', 'Braithwaite', 'fiction', 'Penguin', 1, 'Galapagos hawk');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('135440420-3', 'Half A Life', 'Naipaul, V S', 'fiction', null, 2, 'Jaguarundi');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('436367915-8', 'Discovery of India, The', 'Nehru, Jawaharlal', 'history', null, 1, 'Pintail, white-cheeked');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('979359773-9', 'Apulki', 'Deshpande, P L', 'nonfiction', null, 2, 'Potoroo');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('993943072-8', 'Unpopular Essays', 'Russell, Bertrand', 'philosophy', null, 2, 'Monkey, bleeding heart');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('223268435-0', 'Deceiver, The', 'Forsyth, Frederick', 'fiction', null, 2, 'Striated heron');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('401054912-2', 'Veil: Secret Wars of the CIA', 'Woodward, Bob', 'history', null, 2, 'Black-winged stilt');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('909547907-2', 'Char Shabda', 'Deshpande, P L', 'nonfiction', null, 2, 'North American beaver');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('482839587-3', 'Rosy is My Relative', 'Durrell, Gerald', 'fiction', null, 2, 'Scarlet macaw');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('322873925-2', 'Moon and Sixpence, The', 'Maugham, William S', 'fiction', null, 1, 'Greater adjutant stork');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('034640103-8', 'Political Philosophers', null, 'philosophy', null, 1, 'Slender-billed cockatoo');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('590182298-6', 'Short History of the World, A', 'Wells, H G', 'history', null, 1, 'Red meerkat');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('870674664-0', 'Trembling of a Leaf, The', 'Maugham, William S', 'fiction', null, 2, 'Red-tailed hawk');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('227323615-8', 'Doctor on the Brain', 'Gordon, Richard', 'fiction', null, 2, 'Mexican beaded lizard');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('791130168-9', 'Simpsons & Their Mathematical Secrets', 'Singh, Simon', 'science', null, 1, 'Common palm civet');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('448412141-7', 'Pattern Classification', 'Duda, Hart', 'data_science', null, 2, 'White-mantled colobus');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('856235160-1', 'From Beirut to Jerusalem', 'Friedman, Thomas', 'history', null, 2, 'Lion, south american sea');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('897496711-1', 'Code Book, The', 'Singh, Simon', 'science', null, 2, 'Owl, great horned');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('889632921-3', 'Age of the Warrior, The', 'Fisk, Robert', 'history', null, 2, 'Malay squirrel (unidentified)');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('063946403-3', 'Final Crisis', null, 'comic', null, 1, 'Bandicoot, long-nosed');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('014452289-6', 'Killing Joke, The', null, 'comic', null, 2, 'Tropical buckeye butterfly');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('250553215-X', 'Flashpoint', null, 'comic', null, 2, 'Leadbeateri''s ground hornbill');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('457809411-1', 'Batman Earth One', null, 'comic', null, 2, 'Northern elephant seal');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('799172199-X', 'Crisis on Infinite Earths', null, 'comic', null, 2, 'Water legaan');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('477702505-5', 'Numbers Behind Numb3rs, The', 'Devlin, Keith', 'science', null, 2, 'Galah');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('029217750-X', 'Superman Earth One - 1', null, 'comic', null, 2, 'Butterfly, tropical buckeye');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('741598778-0', 'Superman Earth One - 2', null, 'comic', null, 2, 'Grouse, sage');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('733844286-X', 'Justice League: Throne of Atlantis', null, 'comic', null, 2, 'Sambar');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('880757708-9', 'Justice League: The Villain''s Journey', null, 'comic', null, 2, 'Plover, three-banded');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('918465760-X', 'Death of Superman, The', null, 'comic', null, 2, 'Dingo');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('771507085-8', 'History of the DC Universe', null, 'comic', null, 2, 'Owl, burrowing');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('146732091-9', 'Batman: The Long Halloween', null, 'comic', null, 2, 'Hedgehog, south african');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('369141660-8', 'Life in Letters, A', 'Steinbeck, John', 'nonfiction', null, 2, 'Gull, swallow-tail');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('414455641-7', 'Information, The', 'Gleick, James', 'science', null, 2, 'Starling, superb');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('949431822-6', 'Journal of Economics, vol 106 No 3', null, 'economics', null, 2, 'Wolf spider');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('863305225-3', 'Elements of Information Theory', 'Thomas, Joy', 'data_science', null, 2, 'Brazilian tapir');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('144317261-8', 'Power Electronics - Rashid', 'Rashid, Muhammad', 'computer_science', null, 2, 'Gnu, brindled');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('200227766-4', 'Power Electronics - Mohan', 'Mohan, Ned', 'computer_science', null, 2, 'Ass, asiatic wild');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('489317825-3', 'Neural Networks', 'Haykin, Simon', 'data_science', null, 2, 'Wolf, common');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('063658245-0', 'Grapes of Wrath, The', 'Steinbeck, John', 'fiction', null, 2, 'Mountain duck');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('938280618-0', 'Vyakti ani Valli', 'Deshpande, P L', 'nonfiction', null, 1, 'Wild water buffalo');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('151763129-7', 'Statistical Learning Theory', 'Vapnik, Vladimir', 'data_science', null, 2, 'Eastern quoll');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('232323776-4', 'Empire of the Mughal - The Tainted Throne', 'Rutherford, Alex', 'history', null, 1, 'Whale, southern right');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('083494165-1', 'Empire of the Mughal - Brothers at War', 'Rutherford, Alex', 'history', null, 2, 'Tortoise, radiated');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('034072155-3', 'Empire of the Mughal - Ruler of the World', 'Rutherford, Alex', 'history', null, 2, 'Bustard, kori');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('350310701-0', 'Empire of the Mughal - The Serpent''s Tooth', 'Rutherford, Alex', 'history', null, 1, 'Rufous-collared sparrow');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('042617224-8', 'Empire of the Mughal - Raiders from the North', 'Rutherford, Alex', 'history', null, 2, 'Galapagos dove');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('385471974-4', 'Mossad', 'Baz-Zohar, Michael', 'history', null, 2, 'Springbok');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('842088297-6', 'Jim Corbett Omnibus', 'Corbett, Jim', 'nonfiction', null, 1, 'Brown antechinus');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('879852807-6', '20000 Leagues Under the Sea', 'Verne, Jules', 'fiction', null, 2, 'Groundhog');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('731188136-6', 'Batatyachi Chal', 'Deshpande P L', 'fiction', null, 2, 'Fox, blue');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('939875549-1', 'Hafasavnuk', 'Deshpande P L', 'fiction', null, 2, 'Potoroo');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('434549253-X', 'Urlasurla', 'Deshpande P L', 'fiction', null, 1, 'King vulture');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('325336613-8', 'Pointers in C', 'Kanetkar, Yashwant', 'computer_science', null, 2, 'Bobcat');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('446750239-4', 'Cathedral and the Bazaar, The', 'Raymond, Eric', 'computer_science', null, 2, 'Bear, black');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('354229130-7', 'Design with OpAmps', 'Franco, Sergio', 'computer_science', null, 2, 'Bear, black');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('007064251-6', 'Think Complexity', 'Downey, Allen', 'data_science', null, 2, 'Black-cheeked waxbill');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('456306789-X', 'Devil''s Advocate, The', 'West, Morris', 'fiction', null, 2, 'Richardson''s ground squirrel');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('159787253-9', 'Ayn Rand Answers', 'Rand, Ayn', 'philosophy', null, 2, 'Collared lemming');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('704057794-1', 'Philosophy: Who Needs It', 'Rand, Ayn', 'philosophy', null, 2, 'Armadillo, common long-nosed');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('309418783-8', 'World''s Great Thinkers, The', null, 'philosophy', null, 1, 'Cat, kaffir');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('110414385-2', 'Data Analysis with Open Source Tools', 'Janert, Phillip', 'data_science', null, 2, 'Eastern diamondback rattlesnake');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('103400501-4', 'Broca''s Brain', 'Sagan, Carl', 'science', null, 2, 'White-bellied sea eagle');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('037110373-8', 'Men of Mathematics', 'Bell, E T', 'mathematics', null, 2, 'Cormorant, little');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('258548263-4', 'Oxford book of Modern Science Writing', 'Dawkins, Richard', 'science', null, 2, 'Red sheep');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('231174935-8', 'Justice, Judiciary and Democracy', 'Ranjan, Sudhanshu', 'philosophy', null, 2, 'Ibis, glossy');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('494227959-3', 'Arthashastra, The', 'Kautiyla', 'philosophy', null, 1, 'Potoroo');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('697497766-2', 'We the People', 'Palkhivala', 'philosophy', null, 2, 'Lemur, lesser mouse');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('915265277-7', 'We the Nation', 'Palkhivala', 'philosophy', null, 1, 'Blesbok');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('208165871-2', 'Courtroom Genius, The', 'Sorabjee', 'nonfiction', null, 2, 'Spoonbill, white');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('548255933-5', 'Dongri to Dubai', 'Zaidi, Hussain', 'nonfiction', null, 2, 'Otter, canadian river');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('599842717-3', 'History of England, Foundation', 'Ackroyd, Peter', 'history', null, 2, 'African lynx');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('070171169-8', 'City of Djinns', 'Dalrymple, William', 'history', null, 1, 'Rhesus macaque');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('691422426-9', 'India''s Legal System', 'Nariman', 'nonfiction', null, 2, 'Pale-throated three-toed sloth');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('015762236-3', 'More Tears to Cry', 'Sassoon, Jean', 'fiction', null, 2, 'Ovenbird');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('466966800-5', 'Ropemaker, The', 'Dickinson, Peter', 'fiction', null, 2, 'Honey badger');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('218522768-8', 'Angels & Demons', 'Brown, Dan', 'fiction', null, 2, 'Common wombat');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('603767318-7', 'Judge, The', null, 'fiction', null, 2, 'Springhare');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('885054425-1', 'Attorney, The', null, 'fiction', null, 2, 'Possum, common brushtail');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('322381927-4', 'Prince, The', 'Machiavelli', 'philosophy', null, 1, 'Mynah, common');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('044528827-2', 'Eyeless in Gaza', 'Huxley, Aldous', 'fiction', null, 2, 'American crow');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('401572665-0', 'Tales of Beedle the Bard', 'Rowling, J K', 'fiction', null, 2, 'Long-tailed jaeger');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('655655959-8', 'Girl with the Dragon Tattoo', 'Larsson, Steig', 'fiction', null, 2, 'Kinkajou');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('778380004-1', 'Girl who kicked the Hornet''s Nest', 'Larsson, Steig', 'fiction', null, 1, 'Phalarope, grey');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('962249547-8', 'Girl who played with Fire', 'Larsson, Steig', 'fiction', null, 2, 'Vine snake (unidentified)');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('704128420-4', 'Batman Handbook', null, 'comic', null, 2, 'Swan, trumpeter');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('373015798-1', 'Murphy''s Law', null, 'nonfiction', null, 1, 'Purple moorhen');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('420651840-8', 'Structure and Randomness', 'Tao, Terence', 'mathematics', null, 1, 'Owl, australian masked');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('542931263-0', 'Image Processing with MATLAB', 'Eddins, Steve', 'signal_processing', null, 1, 'Cat, european wild');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('272714796-1', 'Animal Farm', 'Orwell, George', 'fiction', null, 1, 'Ring-tailed gecko');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('407881621-5', 'Idiot, The', 'Dostoevsky, Fyodor', 'fiction', null, 2, 'Otter, small-clawed');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('658958878-3', 'Christmas Carol, A', 'Dickens, Charles', 'fiction', null, 2, 'Gull, lava');
insert into tblProducts (isbn, product_name, author, genre, publisher, product_type, description) values ('009124224-X', 'Fundamentals of Wavelets', 'Goswami, Jaideva', 'signal_processing', 'Wiley', 1, 'Western palm tanager (unidentified)');
